### ISSUE TITLE
client.info('Keyspace', callback) no longer works.

### ISSUE THREAD

**Issue by ksylvan** [NodeRedis/node_redis#1003]
Version: 2.5.0
Node 5.8.0

client.info('Keyspace', callback) used to work, but now I get this error:

    $ node
    > var redis = require('redis');
    undefined
    > var client = redis.createClient({host: 'redis'});
    undefined
    > client.info('Keyspace', console.log)
    true
    > TypeError: callback is not a function
        at Object.callbackOrEmit [as callback_or_emit] (/usr/src/app/node_modules/redis/lib/utils.js:73:9)
        at Command.<anonymous> (/usr/src/app/node_modules/redis/lib/individualCommands.js:73:15)
        at bound (domain.js:287:14)
        at Command.runBound (domain.js:300:12)
        at normal_reply (/usr/src/app/node_modules/redis/index.js:662:21)
        at RedisClient.return_reply (/usr/src/app/node_modules/redis/index.js:722:9)
        at JavascriptReplyParser.RedisClient.reply_parser.Parser.returnReply (/usr/src/app/node_modules/redis/index.js:146:18)
        at JavascriptReplyParser.run (/usr/src/app/node_modules/redis-parser/lib/javascript.js:136:18)
        at JavascriptReplyParser.execute (/usr/src/app/node_modules/redis-parser/lib/javascript.js:111:10)
        at Socket.<anonymous> (/usr/src/app/node_modules/redis/index.js:223:27)

**Comment by BridgeAR** [comment]
@ksylvan thanks a lot for reporting this right away. I forgot about the optional section argument :/. Fixed in the just released v.2.5.1.

**Comment by ksylvan** [comment]
:+1: 

Verified fixed.

    /usr/src/app $ node
    > var redis = require('redis');
    undefined
    > var client = redis.createClient({host: 'redis'});
    undefined
    > client.info('Keyspace', console.log)
    true
    > null '# Keyspace\r\n'
    > client.set('x', 'y'); client.set('a', 'b')
    true
    > client.info('Keyspace', console.log)
    true
    > null '# Keyspace\r\ndb0:keys=2,expires=0,avg_ttl=0\r\n'
