### ISSUE TITLE
Redis module throwing error when monitoring is on

### ISSUE THREAD

**Issue by srehanuddin** [NodeRedis/node_redis#1005]
Hi,

When i turn monitoring on and then calling redis.get function, i am getting this error

```
reply = reply.toString();
                     ^

TypeError: Cannot read property 'toString' of null
    at monitor (e:\Zaavia\_Zaavia-Projects\Panacea-BBIS-WorkingRepo\node_modules\redis\index.js:645:22)
    at RedisClient.return_reply (e:\Zaavia\_Zaavia-Projects\Panacea-BBIS-WorkingRepo\node_modules\redis\index.js:728:9)
    at JavascriptReplyParser.RedisClient.reply_parser.Parser.returnReply (e:\Zaavia\_Zaavia-Projects\Panacea-BBIS-WorkingRepo\node_modules\redis\index.js:146:18)
    at JavascriptReplyParser.run (e:\Zaavia\_Zaavia-Projects\Panacea-BBIS-WorkingRepo\node_modules\redis-parser\lib\javascript.js:136:18)
    at JavascriptReplyParser.execute (e:\Zaavia\_Zaavia-Projects\Panacea-BBIS-WorkingRepo\node_modules\redis-parser\lib\javascript.js:111:10)
    at Socket.<anonymous> (e:\Zaavia\_Zaavia-Projects\Panacea-BBIS-WorkingRepo\node_modules\redis\index.js:223:27)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)
```

```
redis.get("ABC", function(err, data){
            console.log(err);
            console.log(data);
        })
```

**Comment by BridgeAR** [comment]
@srehanuddin the monitor client may not fire any other commands than quit after activating [monitor](https://redis.io/commands/monitor). You have to open a new client and then fire the commands with that one instead. The monitor client is going to receive everything that is happening with the other client.

**Comment by srehanuddin** [comment]
@BridgeAR thanks alot, that worked for me.

**Comment by BridgeAR** [comment]
@srehanuddin you're welcome, I'm glad I could help.

**Comment by BridgeAR** [comment]
@srehanuddin I'm sorry I actually made a mistake by believing the former implementation was the way it should be but after digging deeper I realized that you can indeed use monitor and fire arbitrary commands with the same client.

I have a fix for this and it is going to be released very soon.

**Comment by srehanuddin** [comment]
@BridgeAR, thanks this approach would save server resources.
