### ISSUE TITLE
zadd fails when using a key namespace

### ISSUE THREAD

**Issue by assertnotnull** [NodeRedis/node_redis#1015]
* **Version**: redis: 2.8.4 & node_redis: 2.5.3
* **Platform**: Node 5.8.0
* **Description**: When doing `zadd('name:' + id, value1, value2)` it fails with this stack trace:

```
[Error: WRONGTYPE Operation against a key holding the wrong kind of value] command: 'ZADD', code: 'WRONGTYPE' }
Error: WRONGTYPE Operation against a key holding the wrong kind of value
    at JavascriptReplyParser.parseResult (/home/pgauthier/Projets/js/adserving-controller/node_modules/redis-parser/lib/javascript.js:86:16)
    at JavascriptReplyParser.tryParsing (/home/pgauthier/Projets/js/adserving-controller/node_modules/redis-parser/lib/javascript.js:116:21)
    at JavascriptReplyParser.run (/home/pgauthier/Projets/js/adserving-controller/node_modules/redis-parser/lib/javascript.js:140:22)
    at JavascriptReplyParser.execute (/home/pgauthier/Projets/js/adserving-controller/node_modules/redis-parser/lib/javascript.js:111:10)
    at Socket.<anonymous> (/home/pgauthier/Projets/js/adserving-controller/node_modules/redis/index.js:223:27)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
```

Yet it's possible to do it from redis-cli

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by BridgeAR** [comment]
The returned error is from Redis itself. You try to use the same key for different operations. Please check the redis docs [1](http://redis.io/topics/data-types-intro); [2](redis.io/commands/zadd).
