### ISSUE TITLE
Cannot Connect with remote redis server

### ISSUE THREAD

**Issue by willin** [NodeRedis/node_redis#1024]
```
message: Redis connection lost and commands aborted in uncertain state. They might have been processed.
code: UNCERTAIN_STATE
stack: Error: Redis connection lost and commands aborted in uncertain state. They might have been processed.
    at RedisClient.connection_gone (/home/wulian/cloud/fish/node_modules/redis/index.js:576:17)
    at RedisClient.on_error (/home/wulian/cloud/fish/node_modules/redis/index.js:346:10)
    at Socket.<anonymous> (/home/wulian/cloud/fish/node_modules/redis/index.js:231:14)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1253:8)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)
------------------
```

**Comment by BridgeAR** [comment]
@willin the error message indicates that your connection dropped after the connection was established and some commands were fired to your server but the server did not yet respond to those requests.

This should not be an error with node_redis but with your server connection or your code.
But as you did not post anything else besides the error I'm not able to help you any further. Please fill out all the requested data as stated in the issue template.

**Comment by BridgeAR** [comment]
Ping
