### ISSUE TITLE
About Error Stack when use multi()

### ISSUE THREAD

**Issue by CoderIvan** [NodeRedis/node_redis#1053]
* **Version**: 2.6.0-2
* **Platform**: Node.js 5.11.0 Ubuntu 14.04
* **Description**: 

I want to get line number of code which cause error. For example:

```javascript
'use strict'

const redis = require('redis')

const redisOption = {
	host: 'localhost',
	port: '6379',
	db: 15
}

let client = redis.createClient(redisOption)
let value
client.multi()
	.psetex('1', 5000, value)
	.exec((err, replies) => {
		if (err) {
			console.error(err.stack || err)
		} else {
			console.log(replies)
		}
		client.end(false)
	})
```

but i get error stack like that:
```
ReplyError: EXECABORT Transaction discarded because of previous errors.
    at JavascriptReplyParser.Parser.returnError (/home/ivan/project/brickyard/plugins/unified/gateway/plugins/core/cache/node_modules/redis/index.js:193:31)
    at JavascriptReplyParser.run (/home/ivan/project/brickyard/plugins/unified/gateway/plugins/core/cache/node_modules/redis-parser/lib/javascript.js:135:18)
    at JavascriptReplyParser.execute (/home/ivan/project/brickyard/plugins/unified/gateway/plugins/core/cache/node_modules/redis-parser/lib/javascript.js:112:10)
    at Socket.<anonymous> (/home/ivan/project/brickyard/plugins/unified/gateway/plugins/core/cache/node_modules/redis/index.js:269:27)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:534:20)
```

Then, I can't get error line number of code

**Comment by BridgeAR** [comment]
The reason is that the error created in a place where there's currently no connection to the original calling function. 
This won't change for production mode, as it would otherwise significantly decrease the performance but it is planned to improve the error stack for node_redis v.2.7 while in `development` or `debug_mode`.
