### ISSUE TITLE
Script attempted to access unexisting global variable 'bit' 

### ISSUE THREAD

**Issue by aaronroberson** [NodeRedis/node_redis#1058]
* **Version**: node_redis v2.6.0-1 and Redis server v=2.8.17 sha=00000000:0 malloc=libc bits=64 build=454d996953bc053b
* **Platform**: This is happening on my Macbook during development and on Ubuntu 14 in our staging enviornment
* **Description**: We are using bull as a redis queue. When adding a job to the queue (`settlementGameQueue.add({game: game}, {delay: delay});`), we get the following error:
```
Unhandled rejection Error: ERR Error running script (call to f_1f46a25dd9f50b1331d5c86b90ba4dce1e15cd8f): @enable_strict_lua:14: user_script:3: Script attempted to access unexisting global variable 'bit' 
    at JavascriptReplyParser.parseResult (/Users/aaronroberson/Sites/gsn/draft4-server-api/node_modules/redis-parser/lib/javascript.js:90:16)
    at JavascriptReplyParser.tryParsing (/Users/aaronroberson/Sites/gsn/draft4-server-api/node_modules/redis-parser/lib/javascript.js:117:21)
    at JavascriptReplyParser.run (/Users/aaronroberson/Sites/gsn/draft4-server-api/node_modules/redis-parser/lib/javascript.js:131:22)
    at JavascriptReplyParser.execute (/Users/aaronroberson/Sites/gsn/draft4-server-api/node_modules/redis-parser/lib/javascript.js:112:10)
    at Socket.<anonymous> (/Users/aaronroberson/Sites/gsn/draft4-server-api/node_modules/bull/node_modules/redis/index.js:223:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by aaronroberson** [comment]
I installed hiredis and I still get the same error, but hiredis is in the stacktrace. I also downgraded to node_redis 2.5.3:

```Unhandled rejection Error: ERR Error running script (call to f_1f46a25dd9f50b1331d5c86b90ba4dce1e15cd8f): @enable_strict_lua:14: user_script:3: Script attempted to access unexisting global variable 'bit' 
    at Error (native)
    at HiredisReplyParser.parseData (/Users/aaronroberson/Sites/gsn/draft4-server-api/node_modules/redis-parser/lib/hiredis.js:13:28)
    at HiredisReplyParser.execute (/Users/aaronroberson/Sites/gsn/draft4-server-api/node_modules/redis-parser/lib/hiredis.js:24:22)
    at Socket.<anonymous> (/Users/aaronroberson/Sites/gsn/draft4-server-api/node_modules/redis/index.js:223:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by Salakar** [comment]
Is this a local redis server? Could you try another server and see if you have the issue, looks like your redis server is loading certain libs, specifically `bit` which is used here: https://github.com/OptimalBits/bull/blob/c61e3ff88277f33ebec30c060588f85b31ff49c9/lib/scripts.js#L90

**Comment by BridgeAR** [comment]
The error is thrown by Redis itself and the stacktrace is just not helpful currently. Seems like bull tries to use a variable that is not set at execution time.
So it's not a error in node_redis and I suggest to open a new issue in bull for it.

**Comment by aaronroberson** [comment]
@Salakar On my local MacBook I have redis-server running and I'm connecting to it all on the same machine. However, I'm getting the exact same error on our staging server which connects to a sperate box running redis.

@BridgeAR Looking at the code that @Salakar linked to, it does, in fact, look like bull is referencing a variable which doesn't exist. I will open a ticket there as you've suggested.

Thank you both for the quick reply!
