### ISSUE TITLE
error running tests

### ISSUE THREAD

**Issue by ORESoftware** [NodeRedis/node_redis#1065]
I just cloned the repo and ran the tests, I am getting this weird error

`ReplyError: Ready check failed: NOAUTH Authentication required.`

Looks like that means that Redis is started up, but it needs auth. Looks like auth is provided in the form of certs and not username/password. Any idea why the certs might not be good? 

Would like to get the tests running, thanks, I am on the latest version of this lib and node.

**Comment by ORESoftware** [comment]
here's the actual stack trace

```
ReplyError: Ready check failed: NOAUTH Authentication required.
	    at JavascriptReplyParser.Parser.returnError (/Users/Olegzandr/WebstormProjects/node_redis/index.js:193:31)
	    at JavascriptReplyParser.run (/Users/Olegzandr/WebstormProjects/node_redis/node_modules/redis-parser/lib/javascript.js:135:18)
	    at JavascriptReplyParser.execute (/Users/Olegzandr/WebstormProjects/node_redis/node_modules/redis-parser/lib/javascript.js:112:10)
```

**Comment by BridgeAR** [comment]
The stack trace is not relevant and has no connection to the calling function currently. More relevant would be what tests fail first.
Auth is always provided with a username and password and the certs are needed for tls. You might have to install stunnel to run the tests.

**Comment by ORESoftware** [comment]
Ah, stunnel, will let you know if I figure it out thanks
