### ISSUE TITLE
Redis reconnect works not as it is supposed

### ISSUE THREAD

**Issue by pavelsc** [NodeRedis/node_redis#1077]
I am using in my worker the next initialization:

```
redis: {
	init: function (parent) {
		var self = this;
		self.parent = parent;
		self.cfg = {
			port: self.parent.cfg['redis']['port'],
			host: self.parent.cfg['redis']['host'],
			password: self.parent.cfg['redis']['password']
		};
		self.client = redis.createClient(self.cfg.port, self.cfg.host, {retry_strategy: function (options) {
			if (options.error) {
				log.warn("Redis error:", options);
			}
			if (options.error.code === 'ECONNREFUSED') {
				// End reconnecting on a specific error and flush all commands with a individual error
				return new Error('The server refused the connection');
			}
			if (options.error.code === 'ECONNRESET') {
				return new Error('The server reset the connection');
			}
			if (options.error.code === 'ETIMEDOUT') {
				return new Error('The server timeouted the connection');
			}
			if (options.total_retry_time > 1000 * 60 * 60) {
				// End reconnecting after a specific timeout and flush all commands with a individual error
				return new Error('Retry time exhausted');
			}
			if (options.times_connected > 5) {
				// End reconnecting with built in error
				return new Error('Retry attempts ended');
			}
			// reconnect after
			return 1000;
		}});
		self.client.on('error', function (err) {
			log.error({err: err}, 'Listener.redis.client error: %s', err);
			process.exit(1);
		});
		self.auth = Q.nbind(self.client.auth, self.client);
		self.incr = Q.nbind(self.client.incr, self.client);
		self.hmset = Q.nbind(self.client.hmset, self.client);
		self.hgetall = Q.nbind(self.client.hgetall, self.client);
		self.set = Q.nbind(self.client.set, self.client);
		self.get = Q.nbind(self.client.get, self.client);
		self.zadd = Q.nbind(self.client.zadd, self.client);
		self.sismember = Q.nbind(self.client.sismember, self.client);
		return self.auth(self.cfg.password);
	}
}
```

So I suppose it should reconnect 5 times, one reconnect per second in case of failed connection and then raise an error. And this is what I see in supervisor's log:

```
{"name":"ami","hostname":"Ast2","pid":28257,"level":40,"msg":"Redis error: { attempt: 1,\n  error: [Error: Stream connection ended],\n  total_retry_time: 0,\n  times_connected: 1 }","time":"2016-06-01T10:39:45.426Z","v":0}
{"name":"ami","hostname":"Ast2","pid":28257,"level":40,"msg":"Redis error: { attempt: 1,\n  error: [Error: Stream connection ended],\n  total_retry_time: 0,\n  times_connected: 2 }","time":"2016-06-01T10:49:47.446Z","v":0}
{"name":"ami","hostname":"Ast2","pid":28257,"level":40,"msg":"Redis error: { attempt: 1,\n  error: [Error: Stream connection ended],\n  total_retry_time: 0,\n  times_connected: 3 }","time":"2016-06-01T10:59:49.399Z","v":0}
{"name":"ami","hostname":"Ast2","pid":28257,"level":40,"msg":"Redis error: { attempt: 1,\n  error: [Error: Stream connection ended],\n  total_retry_time: 0,\n  times_connected: 4 }","time":"2016-06-01T11:09:50.437Z","v":0}
{"name":"ami","hostname":"Ast2","pid":28257,"level":40,"msg":"Redis error: { attempt: 1,\n  error: [Error: Stream connection ended],\n  total_retry_time: 0,\n  times_connected: 5 }","time":"2016-06-01T11:19:52.396Z","v":0}
{"name":"ami","hostname":"Ast2","pid":28257,"level":40,"msg":"Redis error: { attempt: 1,\n  error: [Error: Stream connection ended],\n  total_retry_time: 0,\n  times_connected: 6 }","time":"2016-06-01T11:29:53.408Z","v":0}
{"name":"ami","hostname":"Ast2","pid":28257,"level":50,"err":{"message":"Retry attempts ended","name":"Error","stack":"Error: Retry attempts ended\n    at Object.self.client.redis.createClient.retry_strategy (/var/daemon/listener.js:102:15)\n    at RedisClient.connection_gone (/node_modules/redis/index.js:552:41)\n    at Socket.<anonymous> (/node_modules/redis/index.js:241:14)\n    at Socket.g (events.js:273:16)\n    at emitNone (events.js:85:20)\n    at Socket.emit (events.js:179:7)\n    at endReadableNT (_stream_readable.js:906:12)\n    at nextTickCallbackWith2Args (node.js:474:9)\n    at process._tickCallback (node.js:388:17)"},"msg":"Listener.redis.client error: Error: Retry attempts ended","time":"2016-06-01T11:29:53.411Z","v":0}
{"name":"ami","hostname":"Ast2","pid":28606,"level":40,"msg":"Redis error: { attempt: 1,\n  error: [Error: Stream connection ended],\n  total_retry_time: 0,\n  times_connected: 1 }","time":"2016-06-01T11:40:21.459Z","v":0}
{"name":"ami","hostname":"Ast2","pid":28606,"level":40,"msg":"Redis error: { attempt: 1,\n  error: [Error: Stream connection ended],\n  total_retry_time: 0,\n  times_connected: 2 }","time":"2016-06-01T11:50:23.474Z","v":0}
{"name":"ami","hostname":"Ast2","pid":28606,"level":40,"msg":"Redis error: { attempt: 1,\n  error: [Error: Stream connection ended],\n  total_retry_time: 0,\n  times_connected: 3 }","time":"2016-06-01T12:00:25.475Z","v":0}
{"name":"ami","hostname":"Ast2","pid":28606,"level":40,"msg":"Redis error: { attempt: 1,\n  error: [Error: Stream connection ended],\n  total_retry_time: 0,\n  times_connected: 4 }","time":"2016-06-01T12:19:42.429Z","v":0}
{"name":"ami","hostname":"Ast2","pid":28606,"level":40,"msg":"Redis error: { attempt: 1,\n  error: [Error: Stream connection ended],\n  total_retry_time: 0,\n  times_connected: 5 }","time":"2016-06-01T12:29:44.482Z","v":0}
{"name":"ami","hostname":"Ast2","pid":28606,"level":40,"msg":"Redis error: { attempt: 1,\n  error: [Error: Stream connection ended],\n  total_retry_time: 0,\n  times_connected: 6 }","time":"2016-06-01T12:42:46.537Z","v":0}
{"name":"ami","hostname":"Ast2","pid":28606,"level":50,"err":{"message":"Retry attempts ended","name":"Error","stack":"Error: Retry attempts ended\n    at Object.self.client.redis.createClient.retry_strategy (/var/daemon/listener.js:102:15)\n    at RedisClient.connection_gone (/node_modules/redis/index.js:552:41)\n    at Socket.<anonymous> (/node_modules/redis/index.js:241:14)\n    at Socket.g (events.js:273:16)\n    at emitNone (events.js:85:20)\n    at Socket.emit (events.js:179:7)\n    at endReadableNT (_stream_readable.js:906:12)\n    at nextTickCallbackWith2Args (node.js:474:9)\n    at process._tickCallback (node.js:388:17)"},"msg":"Listener.redis.client error: Error: Retry attempts ended","time":"2016-06-01T12:42:46.541Z","v":0}
```

Why times_connected increments every time while reconnected successfully? This is wrong behavior because it raises an error "Retry attempts ended".  Am I right?

* **Version**: 5.5.0
* **Platform**: Linux Ast2 4.0.4-aufs 
* **Description**: Redis reconnect works not as it is supposed

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by BridgeAR** [comment]
I think you check the wrong value for what you want to achieve. The `times_connected` indicates the total times the client connected to the server. The `attempt` indicates how many times the client tried to reconnect since the connection dropped. And that is always the first attempt in your case.

**Comment by pavelsc** [comment]
@BridgeAR so how do you think why does "Retry attempts ended" occur? There are no attempts in log before that.

**Comment by BridgeAR** [comment]
@pavelsc you create that error on your own in the retry_strategy function by returning that error to node_redis.
