### ISSUE TITLE
Redis failed to connect to UNIX Socket and throwing UNHANDLED Error

### ISSUE THREAD

**Issue by anirbanroydas** [NodeRedis/node_redis#1155]
I have been trying to create the redis client but unable to do so. The details are : 

**Versions :**
redis-server@3.2.1
node@v6.5.0
node_redis@2.6.2 (redis@2.6.2)

**System :**
Macbook White Mid 2010
Processor: 2.4 GHz Intel Core 2 Duo
Memory: 4 GB 1067 MHz DDR3
OS: Mac OS X El Capitan 10.11.4

My `redis.conf` file's important snippet :-
**redis.conf**

```
bind 127.0.0.1
protected-mode yes
port 6379
unixsocket /usr/local/var/run/redis/redis.sock
unixsocketperm 777
pidfile /usr/local/var/run/reis/redis_6379.pid
requirepass my_custom_password

```

The code which I am running `node test.js`  :-
**test.js**

```
const redis = require('redis');

function retryStrategy(options) {
    if (options.error.code === 'ECONNREFUSED') {
        // End reconnecting on a specific error and flush all commands with a individual error
        return new Error('The server refused the connection');
    }
    if (options.total_retry_time > 1000 * 60 * 60) {
        // End reconnecting after a specific timeout and flush all commands with a individual error
        return new Error('Retry time exhausted');
    }
    if (options.times_connected > 10) {
        // End reconnecting with built in error
        return undefined;
    }

    // reconnect after
    return Math.max(options.attempt * 100, 3000);
}


// Options for redis clinet
let redisClient_Options = {
  host: '127.0.0.1',                                                     
  port: 6379,                                                          
  path: '/usr/loca/var/run/redis/redis.sock',         
  return_buffers: false,                                           

  detect_buffers: false,             
  socket_keepalive: true,            
  no_ready_check: false,            
  enable_offline_queue: true,           
  retry_unfulfilled_commands: false,       
  password: `my_cutom_\
  password`,         
  db: 0,                     
  disable_resubscribing: false,           
  // retry_strategy: retryStrategy        
};


// create redis client
// const redisClient = redis.createClient('/usr/loca/var/run/redis/redis.sock');
const redisClient = redis.createClient(redisClient_Options);

```

Now in my `test.js`, you can see, I have used both the versions of creating the client, one with the options and one without options(but with unix socket). Both of them are throwing errors. Moreover, I have also used the options, once with the `retry_strategy` enabled, and once without `retry_strategy`.

I am furnishing the errors for all the cases. Let me know what am I missing in all these.
1. Creating redis client without options:

```
// test.js
const redisClient = redis.createClient('/usr/loca/var/run/redis/redis.sock');

// stack trace
$ node test.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to /usr/loca/var/run/redis/redis.sock failed - connect ENOENT /usr/loca/var/run/redis/redis.sock
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```
1. Creating redis client with options with retry_strategy as commented:

```
// test.js
// retry_strategy: retryStrategy -> This is commented in redisClient_Options
const redisClient = redis.createClient(redisClient_Options);

// stack trace
$ node test.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to /usr/loca/var/run/redis/redis.sock failed - connect ENOENT /usr/loca/var/run/redis/redis.sock
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```
1. Creating redis client with options with retry_strategy as uncommented:

```
// test.js
// retry_strategy: retryStrategy -> This is uncommented in redisClient_Options
const redisClient = redis.createClient(redisClient_Options);

// stack trace
$ node test.js
events.js:160
      throw er; // Unhandled 'error' event
      ^
AbortError: Redis connection lost and command aborted. It might have been processed.
    at RedisClient.flush_and_error (/Users/Roy/Documents/Test-Hack-Codes/Nodejs-Codes/koatest/node_modules/redis/index.js:350:23)
    at RedisClient.connection_gone (/Users/Roy/Documents/Test-Hack-Codes/Nodejs-Codes/koatest/node_modules/redis/index.js:652:14)
    at RedisClient.on_error (/Users/Roy/Documents/Test-Hack-Codes/Nodejs-Codes/koatest/node_modules/redis/index.js:398:10)
    at Socket.<anonymous> (/Users/Roy/Documents/Test-Hack-Codes/Nodejs-Codes/koatest/node_modules/redis/index.js:272:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Unix socket file permissions:

```
$ ls -l /usr/local/var/run/redis       
total 0
srwxrwxrwx  1 Roy  admin  0 Oct  8 17:07 redis.sock
```

**NOTE:**  If trying to create the client without unix socket, and commenting the path options in the `redisClient_Options`, then client creation does not throw any error both with and without `retry_strategy`.

Need help urgently.

**Comment by anirbanroydas** [comment]
Any help on this issue? @BridgeAR  @mranney  @tj

**Comment by ymc-sise** [comment]
I am not familiar with node_redis. But just by viewing your code, it looks like there is a typo in:

``const redisClient = redis.createClient('/usr/loca/var/run/redis/redis.sock');``

**Comment by loretoparisi** [comment]
Is this issue still open? I've got the same error, after turning off/on a VPN connection to the redis store:

```
AbortError: Redis connection lost and command aborted. It might have been processed.
    at RedisClient.flush_and_error (/.../node_modules/redis/index.js:357:23)
    at RedisClient.connection_gone (/.../node_modules/redis/index.js:659:14)
    at RedisClient.on_error (/.../node_modules/redis/index.js:405:10)
    at Socket.<anonymous> (/.../node_modules/redis/index.js:279:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

**Comment by BridgeAR** [comment]
@anirbanroydas as @ymc-sise already pointed out this is actually a typo in your `path`. Please also be aware that you can only either connect by using `host` and `port` or by using `path`. In this case it'll just always choose the path.

@loretoparisi your connection to your server was interrupted while sending out commands and no response came back for them. That's why you see that error.
