### ISSUE TITLE
redis parser error 

### ISSUE THREAD

**Issue by yarivat** [NodeRedis/node_redis#1181]
ReplyError: Protocol error, got "o" as reply type byte. Please report this.
    at parseType (\node_modules\redis\node_modules\redis-parser\lib\parser.js:271:17)

* **Version**: 2.6 redis-parser :2.3
* **Platform**:  Windows 2012 server

the service we have is a socket.io service which uses node-redis package 
from time to time I get the error log above the letter is changing but the rest of the text is not

the full stuck is:
            ^
ReplyError: Protocol error, got "o" as reply type byte. Please report this.
    at parseType (......\node_modules\redis\node_modules\redis-parser\lib\parser.js:271:17)
    at JavascriptRedisParser.execute (....\node_modules\redis\node_modules\redis-parser\lib\parser.js:480:20)
    at Socket.<anonymous> (....\node_modules\redis\index.js:267:27)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by BridgeAR** [comment]
@yarivat what Node.js version do you use and please have a look at the `buffer` and `offset` attributes on the returned error. I need those to be able to debug this properly.

**Comment by BridgeAR** [comment]
Please reopen if you have any new information.
