### ISSUE TITLE
Error when executing a command within a callback of another command

### ISSUE THREAD

**Issue by Xetrics** [NodeRedis/node_redis#1205]
* **Version**: 2.6.5
* **Platform**: Node v7.6.0 on Arch Linux
* **Description**:  

```
        db.llen("queue", (err, jobs) => {
            this.job_queue = jobs
            
            if(this.job_queue > 0) {
                db.rpop("queue", (err, jobs) => {
                    console.log(err)
                })
            }
        })
```

Throws an error at RPOP. It also throws the same error when i change rpop to llen.

```
{ ReplyError
    at parseError (/home/xetrics/dev/steambots/node_modules/redis-parser/lib/parser.js:181:12)
    at parseType (/home/xetrics/dev/steambots/node_modules/redis-parser/lib/parser.js:291:14) command: 'RPOP', args: [ 'queue' ], code: 'ERR' }
```

**Comment by BridgeAR** [comment]
Please have a look at the error message. The error is returned by Redis itself as it is a ReplyError.
