### ISSUE TITLE
using bluebird creates an interesting error message suggesting an implementation mismatch... not sure if it's a bluebird issue or node-redis issue, no time to check but thought I'd put it here

### ISSUE THREAD

**Issue by finetype** [NodeRedis/node_redis#1209]
_Thanks for wanting to report an issue you've found in node_redis. Please delete
this text and fill in the template below. Please note that the issue tracker is only
for bug reports or feature requests. If you have a question, please ask that on [gitter].
If unsure about something, just do as best as you're able._

_Note that it will be much easier to fix the issue if a test case that reproduces
the problem is provided. It is of course not always possible to reduce your code
to a small test case, but it's highly appreciated to have as much data as possible.
Thank you!_

* **Version**: What node_redis and what redis version is the issue happening on?
* **Platform**: What platform / version? (For example Node.js 0.10 or Node.js 5.7.0 on Windows 7 / Ubuntu 15.10 / Azure)
* **Description**: Description of your issue, stack traces from errors and code that reproduces the issue

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

Saw this error message pop up from a `client.on("error")` handler on program start.

Top of my file looks like this:
```
const redis = require("redis");
const bluebird = require('bluebird');
bluebird.promisifyAll(redis.RedisClient.prototype);
bluebird.promisifyAll(redis.Multi.prototype);

let client;
try {
	client = redis.createClient(6379, 'localhost');
	client.on("error", function (err) {
	    log.error("Redis Error: " + err);
	});
}
catch (e) {
	log.error("\n\n\nREDIS CONNECTION FAILURE\n\n\n", e);
}

```

Saw this in my logs, with my custom handlers line 14 below referring to this `on("error") listener above`.
```
(node:6354) Warning: a promise was created in a handler at net.js:548:20 but was not returned from it, see http://goo.gl/rRqMUw
    at RedisClient.ret [as hsetAsync] (eval at makeNodePromisifiedEval (/home/mmc/code/mmc/mmc-server/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
ERROR: Redis Error: Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 Error
    at Object.error (/home/mmc/code/mmc/mmc-server/server/utils.js:142:17)
    at RedisClient.<anonymous> (/home/mmc/code/mmc/mmc-server/server/route-handlers/get-customers-handlers.js:14:10)
    at emitOne (events.js:96:13)
    at RedisClient.emit (events.js:188:7)
    at RedisClient.on_error (/home/mmc/code/mmc/mmc-server/node_modules/redis/index.js:401:14)
    at Socket.<anonymous> (/home/mmc/code/mmc/mmc-server/node_modules/redis/index.js:279:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

node is 6.9.1
node-redis is 2.6.5
redis is 3.2.8

No observable error from it as far as I can tell other than this message.

Cheers.

**Comment by BridgeAR** [comment]
The bluebird warning indicates that you somewhere have a run away promise. Likely when running a `hsetAsync` command. Please check your code. This has nothing specific to do with node_redis though.
