### ISSUE TITLE
Redis reply parser error: Error: node_redis command queue state error.

### ISSUE THREAD

**Issue by gimenete** [NodeRedis/node_redis#121]
Hi,

I have a test suite for my application. It is growing. And now I'm getting random errors from node_redis. This is a stack trace:

Error Error: Redis reply parser error: Error: node_redis command queue state error. If you can reproduce this, please report it.
    at RedisClient.return_reply (/Users/gimenete/node_modules/redis/index.js:427:15)
    at HiredisReplyParser.<anonymous> (/Users/gimenete/node_modules/redis/index.js:87:14)
    at HiredisReplyParser.emit (events.js:64:17)
    at HiredisReplyParser.execute (/Users/gimenete/node_modules/redis/lib/parser/hiredis.js:35:22)
    at RedisClient.on_data (/Users/gimenete/node_modules/redis/index.js:328:27)
    at Socket.<anonymous> (/Users/gimenete/node_modules/redis/index.js:99:14)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:672:14)
    at IOWatcher.onReadable [as callback](net.js:177:10)

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Error: Error: ERR unknown command '4'
    at Object.callback (/Users/gimenete/node_modules/redis/index.js:686:27)
    at RedisClient.return_error (/Users/gimenete/node_modules/redis/index.js:348:25)
    at HiredisReplyParser.<anonymous> (/Users/gimenete/node_modules/redis/index.js:84:14)
    at HiredisReplyParser.emit (events.js:64:17)
    at HiredisReplyParser.execute (/Users/gimenete/node_modules/redis/lib/parser/hiredis.js:33:22)
    at RedisClient.on_data (/Users/gimenete/node_modules/redis/index.js:328:27)
    at Socket.<anonymous> (/Users/gimenete/node_modules/redis/index.js:99:14)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:672:14)
    at IOWatcher.onReadable [as callback](net.js:177:10)

I don't have an accurate example to reproduce this, sorry. It's becoming more common since my test suite grows.

**Comment by BridgeAR** [comment]
This is very likely fixed => marking as fixed
