### ISSUE TITLE
VPN - AbortError: Redis connection lost and command aborted. It might have been processed.

### ISSUE THREAD

**Issue by loretoparisi** [NodeRedis/node_redis#1216]
* **Version**: `redis 2.7.1`
* **Platform**: `node v6.9.4 / macOS Sierra`
* **Description**: 

I get an `AbortError` when having a active connection to the redis store via tunneling, the VPN turns off and on again:

```
AbortError: Redis connection lost and command aborted. It might have been processed.
    at RedisClient.flush_and_error (/.../node_modules/redis/index.js:357:23)
    at RedisClient.connection_gone (/.../node_modules/redis/index.js:659:14)
    at RedisClient.on_error (/.../node_modules/redis/index.js:405:10)
    at Socket.<anonymous> (/.../node_modules/redis/index.js:279:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by BridgeAR** [comment]
I guess your connection is unstable. Please check that. There is nothing that the client do better.

**Comment by etburke** [comment]
I'm having this same issue. @loretoparisi If you discover your issue please let us know.

**Comment by loretoparisi** [comment]
@BridgeAR @etburke This happens over a VPN connection, apparently when the VPN suffers of latency and/or temporary disconnect/reconnect issues.

**Comment by loretoparisi** [comment]
@etburke I have found a case where this issue was due to redis error code:`ETIMEDOUT`

```
Warning: connect-redis reported a client error: Error: Redis connection to mycache.com:XXXX failed - read ETIMEDOUT
```

**Comment by ChanMQ** [comment]
I have the same problem without vpn in mac. Have you finished it ?

**Comment by freeart** [comment]
I have many errors about it on amazon servers without vpn and they use internal ip between to connect to redis.
