### ISSUE TITLE
events.js:141 - throw er; // Unhandled 'error' event -- after LUA script execution

### ISSUE THREAD

**Issue by dpaczewski** [NodeRedis/node_redis#1218]
* **Version**:
 node_redis -> redis": "^2.7.1"
 redis  -> Redis 2.8.24 (00000000/0) 64 bit @ Gentoo

* **Platform**:
  node -> v4.6.2 @ Windows10 Pro
  
* **Description**: 

C:\Users\Darek\WebstormProjects\game>node c.js
RESULT: [ 'fbd9fe2630af990e472a1f93ee6b60dfe36da394' ]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:911:11)
    at exports._exceptionWithHostPort (util.js:934:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1076:14)

C:\Users\Darek\WebstormProjects\game>

**CODE:**

'use strict';

var redis = require("redis"),
	client = redis.createClient();

function prepareRedisConfig(host, port, password) {
	var redisConf = {};

	redisConf.host = host;

	if(port)
		redisConf.port = port;

	if(password)
		redisConf.password = password;

	return redisConf;
}

function redisTest(host, port, password) {
	var redisConf = prepareRedisConfig(host, port, password)
		, client = redis.createClient(redisConf);

	client.on("error", function (err) {
		console.log("Error " + err);
		return 10;
	});

	var name = 'a4'
		, lua = undefined;

	lua = "local partition_key = \"" + name + "!p\"\n" +
	"local res = redis.call(\"hget\", partition_key, ARGV[1])\n" +
	"if (not res) then\n" +
	"   res = redis.call(\"hincrby\", partition_key, \"index\", 1)\n" +
	"   res = res \% tonumber(ARGV[2])\n" +
	"   redis.call(\"hset\", partition_key, ARGV[1], res)\n" +
	"end\n" +
	"return tonumber(res)\n";

	client.multi().script('load', lua).exec(function(err, result) {
		if(err) {
			console.log("ERROR:", err);
		} else {
			console.log("RESULT:", result);
		}
	});

	client.quit();
	return 1;
}

redisTest('192.168.1.100', 6379, '');

**FROM MONITOR:**

1490476878.337750 [0 192.168.1.101:61957] "info"
1490476878.342055 [0 192.168.1.101:61957] "multi"
1490476878.342127 [0 192.168.1.101:61957] "script" "load" "local partition_key = \"a4!p\"\nlocal res = redis.call(\"hget\", partition_key, ARGV[1])\nif (not res) then\n   res = redis.call(\"hincrby\", partition_key, \"index\", 1)\n   res = res % tonumber(ARGV[2])\n   redis.call(\"hset\", partition_key, ARGV[1], res)\nend\nreturn tonumber(res)\n"
1490476878.342343 [0 192.168.1.101:61957] "exec"

**Comment by dpaczewski** [comment]
Sorry. Didn't see the

`client = redis.createClient()`

... in the upper part of the code. That was the reason for the message.
