### ISSUE TITLE
zscoreAsync Warning

### ISSUE THREAD

**Issue by orangebook** [NodeRedis/node_redis#1228]
* **Version**: ^2.6.3
* **Platform**:  Node.js 7.8.0 on Ubuntu 16.04
* **Description**: 
```bash
(node:9253) Warning: a promise was created in a handler at net.js:551:20 but was not returned from it, see http://goo.gl/rRqMUw
    at RedisClient.ret [as zscoreAsync] (eval at makeNodePromisifiedEval (/home/crazy/Proj/people_counting_statistics/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
```

```javascript
//Redis
exports = module.exports = function (redisClient) {

    var client = redisClient || redis.createClient({port:7006}), multi = client.multi();

    client.on("error", function (err) {
        logger.info("Error " + err);
    });

    client.monitor(function (err, res) {
        if (err) {
            logger.log("Entering monitoring mode is error");
        }
        logger.info("Entering monitoring mode.", res);
    });

    // client.on("monitor", function (time, args, raw_reply) {
    //     logger.info(time + ": " + args, raw_reply);
    // });


    //监听　psubscribe 的客户端　
    client.on("psubscribe", function (channel, count) {
        logger.info("当前的监听频道模式为: ", channel, count);
    });

    client.on("pmessage", function (pattern, channel, message) {
        // logger.info("sub channel " +pattern+ channel + ": " + message);
        stackOutputHandler.forEach(function (handler) {
            handler.apply(client, [pattern, channel, message]);
        });
    });

    //监听 subscribe 的客户端
    client.on("subscribe", function (channel, count) {
        logger.info("当前的监听频道为: ", channel, count);
    });

    client.on("message", function (channel, message) {
        logger.info("my message " + channel + ": " + message);
    });

    //封装Key，并配置过期时间,promise useful
    function set(key, value, expire) {
        if (!expire)
            expire |= 60;
        return new Promise(function (resolve, reject) {
            client.set(key, value, 'EX', expire, function (err, result) {
                if (err) {
                    reject(err);
                }
                resolve(result);
            });
        });
    }

    function get(key) {
        return new Promise(function (resolve, reject) {
            client.get(key, function (err, result) {
                if (err) {
                    reject(err);
                }
                resolve(result);
            })
        });
    }

    /***
     *
     * @param key
     * @return promise interface
     */
    function incrKey(key) {
        return client.incrAsync(key);
    }


//封装hmset,并配置过期时间 Promise valuable
    var hmset = (function () {
        var isExpired = false;

        function hmset(key_group, array, expire) {
            return new Promise(function (resolve, rejct) {
                client.hmsetAsync(key_group, array).then(function (result) {
                    resolve(result);
                    if (expire > 0 && !isExpired) {
                        isExpired = true;
                        client.multi().expire(key_group, expire).exec(function (err, result) {
                            console.log(err, result)
                        });
                    }
                }).catch(function (e) {
                    rejct(e);
                });
            });
        }

        return hmset;
    })();

//万能的expire,Promise valuable
    function expire(key, time) {
        return new Promise(function (resolve, reject) {
            client.multi().expire(key, time).exec(function (err, result) {
                if (err) {
                    reject(err);
                }
                else {
                    resolve(result);
                }
            });
        });
    }

    function hget(key_group, key) {
        return new Promise(function (resolve, reject) {
            client.hmgetAsync(key_group, key).then(function (result) {
                resolve(result);
            }).catch(function (e) {
                reject(e);
            })
        });
    }

    /***
     * just Promise !!(^-*-^)//
     * @param key
     * @param timeout
     */
    function blpop(key, timeout) {
        return new Promise(function (resolve, reject) {
            client.multi().blpop(key, timeout || 0).exec(function (err, result) {
                if (err) {
                    reject(err);
                } else {
                    resolve(result);
                }
            });
        });
    }


    function lpush(key, value) {
        if (value) {
            return client.lpushAsync([key, value]);
        } else {
            throw new Error("value is not undefined");
        }
    }

    /***
     * @description lrange
     * @param key   {String}
     * @param start {integer}
     * @param end   {integer}
     */
    function lrange(key, start = 0, end = -1) {
        return new Promise(function (resolve, reject) {
            client.lrangeAsync([key, start, end]).then(function (result) {
                resolve(result.reverse());
            }).catch(function (err) {
                reject(err);
            })
        });

    }

    /***
     * @description : 将记录写入Redis
     * @param key   {String}    : $ip$date
     * @param array {Array}     : [ count1 ,register_name1,count,register_name ]
     */
    function add2SortedSet(key, array) {
        return new Promise(function (resolve, reject) {
            array.unshift(key);
            client.zadd(array, function (err, result) {
                if (err) {
                    reject(err);
                }
                else {
                    resolve(result);
                }
            })
        });
    }

    /***
     * @description: 合并redis-sorted set
     * @param newSetName  "setB"
     * @param setNameArray ["setQ","setA"]
     */
    function consolidationSortedSet(newSetName, setNameArray) {
        return new Promise(function (resolve, reject) {
            setNameArray.unshift(setNameArray.length);
            setNameArray.unshift(newSetName);
            client.zinterstore(setNameArray, function (err, response) {
                if (err) {
                    reject(err);
                }
                else {
                    resolve(response);
                }
            });
        });
    }

    /***
     * ZINCRBY,为有序集key 的成员member的score值加上增量increment
     * @param key       {String}
     * @param member    {String}
     * @param increase  {number}
     */
    function sortedSetIncr(key, member, increase = 1) {
        return client.zincrbyAsync([key, increase, member]);
    }

    /***
     * @description setName start stop [WITHSCORES]
     *             <p>下标参数 start 和 stop 都以 0 为底，也就是说，以 0 表示有序集第一个成员，以 1 表示有序集第二个成员，以此类推。
     *                你也可以使用负数下标，以 -1 表示最后一个成员， -2 表示倒数第二个成员，以此类推
     *             </p>
     * @param key   {String}
     * @param start {number}
     * @param stop  {number}
     * @param param {String}
     * @return {promise|Array}
     */
    function sortedSetRange(key, start = 0, stop = -1, param = "WITHSCORES") {
        return new Promise(function (resolve, reject) {
            let command = [key, start, stop, param];
            if (param == null || param == "") command.pop();
            client.zrange(command, function (err, response) {
                if (err) {
                    reject(err);
                }
                else {
                    resolve(response);
                }
            });
        })
    }

    /***
     *
     * @param setName
     * @param start
     * @param stop
     * @param param
     */
    function sortedSetRevRange(setName, start = 0, stop = -1, param = "WITHSCORE") {
        return new Promise(function (resolve, reject) {
            let command = [setName, start, stop, param, limit];
            if (param == null || param == "") command.pop();
            client.zrevrange(command, function (err, response) {
                if (err) {
                    reject(err);
                }
                else {
                    resolve(response);
                }
            });
        })
    }

    /***
     * @description ZREMRANGEBYSCORE 默认从小到大排序
     */
    function sortedSetRangeByScore(setName, min, max) {
        return client.zrangebyscoreAsync(setName, min, max);
    }

    /***
     * @description ZREMRANGEBYSCORE 默认从大到小排序
     * @param setName
     * @param min
     * @param max
     */
    function revSortedSetRangeByScore(setName, min, max, param = "WITHSCORES") {
        let command = [setName, min, max, param];
        if (param == null || param == "") command.pop();
        return client.zrevrangebyscoreAsync(command);
    }

    /***
     * 返回有序集 key 中， score 值在 min 和 max 之间
     * (默认包括 score 值等于 min 或 max )的成员的数量。
     * @param setName
     * @param min
     * @param max
     * @returns {*}
     */
    function zcount(setName, min, max) {
        return client.zcountAsync([setName, min, max]);
    }


    /***
     * redis subscribe
     * @param channel
     */
    function input(channel) {
        client.psubscribe(channel);
    }

    /***
     * 汇总消息，进行批处理
     * @param callback(message,client)
     */
    function output(callback) {
        if (typeof (callback) == 'function') {
            stackOutputHandler.push(callback);
        }
        else {
            throw new Error("callback is not function");
        }
    }

    function publish(channel, message) {
        client.publish(channel, message);
    }

    /***
     * @description 判断Key
     * @param key
     * @return Promise with result:OK or err:"ERR:Not Exist"
     */
    function isKeyExist(key) {
        return new Promise(function (resolve, reject) {
            client.exists(key, function (err, result) {
                if (err) {
                    reject(err)
                } else {
                    if (result == 1) {
                        resolve("OK")
                    } else {
                        reject("ERR:Not Exist")
                    }

                }
            })
        });

    }


    return {
        handler: {
            publish: publish,
            input: input,
            output: output
            //由output 完成信息的添加，如天气，星期，register-type,以及redis信息的合并与计数等　
        },
        blpop: blpop,
        set: set,
        get: get,
        hget: hget,
        hmset: hmset,
        exec: client,
        expire: expire,
        add2SortedSet: add2SortedSet,
        consolidationSortedSet: consolidationSortedSet,
        sortedSetRangeByScore: sortedSetRangeByScore,
        sortedSetRange: sortedSetRange,
        sortedSetRevRange: sortedSetRevRange,
        sortedSetIncr: sortedSetIncr,
        zcount: zcount,
        revSortedSetRangeByScore: revSortedSetRangeByScore,
        incrKey: incrKey,
        lpush: lpush,
        lrange: lrange,
        isKeyExist: isKeyExist
    }

}
```

```javascript
function list(key, limit = 15, isChart = false) {
		return new Promise(function (resolve, reject) {
			let type = key.split("$")[2];
			Redis.exec.sortAsync([key, "DESC", "LIMIT", 0, limit]).then(function (result) {

				if (result.length == 0) {
					throw new Error("Not Exit Monitor By Ip")
				}

				let timeSeries = [], chartObj, xList, yList;
				/***
				 ** @description data of format to chart
				 ** {
                 **     x_data:[],
                 **     data:[{register_name:[]},{register2:[]},{register3:[]},[...]],      //default: null
                 **     range_time:{start:192334,end:22456} //default: -infinite +infinite
                 ** }
				 ***/
				if (isChart) {
					xList = [];
					yList = [];
					chartObj = {xAxisData: xList, yAxisData: yList};
				}
				for (let index = result.length - 1; index >= 0; --index) {
					let member = result[index];
					Redis.exec.zscoreAsync(key, member).then(function (response) {
						if (!isChart) {
							let obj = {};
							obj[member] = response;
							timeSeries.push(obj);
							if (timeSeries.length == result.length - 1) {
								return resolve(timeSeries);
							}
						} else {
							chartObj.xAxisData.push(moment(new Date(parseInt(member))).local().format(formatType[type]).toString());
							chartObj.yAxisData.push(response);
							if (chartObj.xAxisData.length == result.length && chartObj.yAxisData.length == result.length) {
								chartObj.range_time = [chartObj.xAxisData[0], moment(new Date(parseInt(member))).local().format(formatType[type]).toString()];
								return resolve(chartObj);
							}
						}
					}).catch(function (err) {
						if (err)
							return reject(err);
					});
				}
			}).catch(function (err) {
				if (err) {
					return reject(err);
				}
			});
		});
	}
```

**Comment by BridgeAR** [comment]
The bluebird warning is correct as you do not return the inner Promise, so it's detected as run away promise.

First you wrap the Redis.exec.sortAsync in a Promise constructor (it is not good to expose the client under exec by the way as exec is a regular command for multi / batch). Then you call that promise and in the result you execute another promise withour returning it (Redis.exec.zscoreAsync). That's what bluebird detects.

As far as I see it your code could be simplified a lot. I recommend to read more about promises and how to handle them :-)
