### ISSUE TITLE
An error thrown inside a command's callback results in an uncaughtException even if an error listener is attached

### ISSUE THREAD

**Issue by kimamula** [NodeRedis/node_redis#1236]
* **Version**: 2.7.1
* **Platform**: Node.js 6.9.0 on CentOS 6.7
* **Description**: 

Executing the following script results in an uncaughtException.

```js
const { createClient } = require('redis');

process.on('uncaughtException', (err) => console.error('uncaughtException', err));

const client = createClient({
  host: 'redis',
  port: 6379
});
client.on('error', (err) => console.error('Client on error', err));

client.get('key', () => {
  throw new Error('Woops!');
});
```

Output:

```
uncaughtException Error: Woops!
    at Command.client.get [as callback] (/home/src/test/directnodetest.js:12:9)
    at normal_reply (/home/src/test/node_modules/redis/index.js:721:21)
    at RedisClient.return_reply (/home/src/test/node_modules/redis/index.js:819:9)
    at JavascriptRedisParser.returnReply (/home/src/test/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/home/src/test/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/home/src/test/node_modules/redis/index.js:274:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
```

Is this an expected behavior?

**Comment by BridgeAR** [comment]
The callback is your own code and therefore this should result in exactly this behavior.
