### ISSUE TITLE
`command queue state error` when unsubscribing and closing at the same time

### ISSUE THREAD

**Issue by Vinno97** [NodeRedis/node_redis#1239]
_I know that both my package and Node version are outdated, but I am reporting this because the error asked me to report it if I can reproduce it._

* **Version**: node_redis v0.12.1 with MSOpenTech Redis 3.0.504 
* **Platform**: Node 4.4.2 on Windows Server 2012

* **Description**: 

I was messing with terminating a websocket connection when another one connected and got the following error when the connections followed eachother quickly:
```
On line on line 729 in  index.js:

Error: node_redis command queue state error. If you can reproduce this, please report it.
    at RedisClient.eval (eval at <anonymous> (eval at <anonymous> (d:\bcm_framework\server.js:1:63)), <anonymous>:1:2)
    at DebugCommandProcessor.i.dispatch_.vscode_evaluate (eval at <anonymous> (d:\bcm_framework\server.js:1:63), <anonymous>:1:2596)
    at RedisClient.return_reply (d:\bcm_framework\node_modules\redis\index.js:729:9)
    at ReplyParser.<anonymous> (d:\bcm_framework\node_modules\redis\index.js:321:14)
    at emitOne (events.js:77:13)
    at ReplyParser.emit (events.js:169:7)
    at ReplyParser.send_reply (d:\bcm_framework\node_modules\redis\lib\parser\javascript.js:300:10)
    at ReplyParser.execute (d:\bcm_framework\node_modules\redis\lib\parser\javascript.js:173:22)
    at RedisClient.on_data (d:\bcm_framework\node_modules\redis\index.js:547:27)
    at Socket.<anonymous> (d:\bcm_framework\node_modules\redis\index.js:102:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
```

It happens when I try to unsubscribe and quit a Redis instance at the same time.
It does not happen when: 
* I slowly step through the code
* Only the unsubscribe function is called
* Only the quit function is called

The function where this code resides has been working for quite a while, but it was never called right after the connection was established. 

This is also not a case where the client is not yet connected because the message/event that caused the disconnect, came through a channel via this very same client

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by BridgeAR** [comment]
Please update to the newest version.
