### ISSUE TITLE
Error in Promise 

### ISSUE THREAD

**Issue by Shadowman4205** [NodeRedis/node_redis#1261]
I am using redis 2.7.1 and bluebird 3.4.6
While i can get data from redis, when i 

> console.log(client.getAsync(key))

i get this Promise

```
Promise {
  _bitField: 134217728,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _trace:
   { Error
       at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (...\website\node_modules\bluebird\js\release\debuggability.js:396:19)
       at RedisClient.ret [as getAsync] (eval at makeNodePromisifiedEval (...\website\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:8:21)
       at _callee$ (...\website\build\webpack:\src\data\server\services\genericServices\TestRedis\index.js:17:1)
       at tryCatch (...\website\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:63:40)
       at Generator.invoke [as _invoke] (...\website\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:337:22)
       at Generator.prototype.(anonymous function) [as next] (...\website\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:96:21)
       at step (...\website\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
       at ...\website\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
       at <anonymous>
       at process._tickDomainCallback (internal/process/next_tick.js:208:7) _parent: undefined, _promisesCreated: 0, _length: 1 } }
```
if i do 

> const data = await client.getAsync(key)

I get my data. 

So what is this error?

**Comment by jdegger** [comment]
You are probably running Bluebird with debugging options enabled. This is an internal stacktrace not meant for you to worry about. The goal is to keep track of the stacktrace for _when_ an actual error occurs they can tell you where it came from.

Node Redis produces longer stacktraces when you the following is true:

```
var betterStackTraces = /development/i.test(process.env.NODE_ENV) || /\bredis\b/i.test(process.env.NODE_DEBUG);
```

**Comment by BridgeAR** [comment]
@Shadowman4205 you did not wait for the promise to fulfill and you get the raw promise when you print `client.getAsync(key)`.
Please read about promises and how they work. You must write something like the following if you do not use await (that is sugar for the part below):
```js
client.getAsync(key).then(console.log)
```
