### ISSUE TITLE
Cannot read property 'callback' of undefined at normal_reply

### ISSUE THREAD

**Issue by ozerbdy** [NodeRedis/node_redis#1275]
* **Version**: 2.8.0
* **Platform**: Node.js 6.11.3, on Azure  
* **Description**:
We are using windows azure redis cache in which we only use the pub/sub functionality for interprocess communication to handle socket.io connections in different clusters(processes). But we do not use it as an socket.io adapter rather we implemented pub/sub and socket.io mechanisms independently. 

**pubSubManager.js**

```javascript

let subscriber;
let publisher;

module.exports.init = function(){

    subscriber = redis.createClient("port", "url",{auth_pass: "password", tls: {servername: "url"}});
    publisher = redis.createClient("port", "url",{auth_pass: "password", tls: {servername: `"url"}});`

    subscriber.on('error', function(error){
        console.error(error);
        RedisErrorLogsRepository.add('subscriber', "Err " + error, '', function(){});
    });

    publisher.on('error', function(error){
        console.error(error);
        RedisErrorLogsRepository.add('publisher', "Err " + error, '', function(){});
    });

    subscriber.on('ready', function(message){
        delog("subscriber is ready", message);
    });

    publisher.on('ready', function(message){
       delog("publisher is ready", message);
    });

    subscriber.on('reconnecting', function(message){
        delog("subscriber is reconnecting", message);
    });

    publisher.on('reconnecting', function(message){
        delog("publisher is reconnecting", message);
    });

    module.exports.subscriber = subscriber;
    module.exports.publisher = publisher;
};

```

**socketIOManager.js**

```javascript

module.exports = {
    initializeEventListeners(socketIO) {

        pubsubManager.subscriber.on("message", function(channel, packet){
            if(channel === SociableConstants.MubsubEvent.EMIT_EVENT){
                const messageData = JSON.parse(packet);
                const socket = clients[messageData.userId];
                if(socket){ //client connected to this process
                    const eventName = messageData.eventName;
                    const data = messageData.data;
                    const id = messageData.id;
                    const userId = messageData.userId;
                    emitWithRetry(socket, id, eventName, data, function (err, result) {
                        if(err){
                            SocketEventLogsRepository.add(id, userId, eventName, data, err, function(){});
                        }
                    })
                }
            }
        });
        pubsubManager.subscriber.subscribe(SociableConstants.MubsubEvent.EMIT_EVENT);

        socketIO.on("connection", function (socket) {
            delog("A Client Connected!", socket.id, "to process with pid:",`${process.pid}`);
            socket.authenticated = false;
            socket.on('authenticate', function(token, ack){
                delog("client trying to authenticate", token);
                if(is.existy(token) && is.string(token) && is.not.empty(token)){
                    UserRepository.getByToken(token, function(err, user){
                        if(!err && user){
                            socket.authenticated = true;
                            const userId = user._id.toString();
                            socket.userId = userId;
                            socket.join(userId);
                            clients[userId] = socket;
                            delog("user successfully authenticated token", token, "userId", userId);
                            ack(true);
                        }else{
                            ack(false);
                        }
                    })
                }else{
                    ack(false);
                }
            });

            socketIO.of('/').adapter.clients((err, clients) =>{
                delog("connected clients", clients, "err",err);
            });

            //delog("from io");
            _.each(socketIO.sockets.sockets, soc => delog(soc.id));

            socket.on('disconnect', function () {
                delog('A Client Get Disconnected', socket.id, "from process with pid:", `${process.pid}`);
                if(socket.userId){
                    delete clients[socket.userId];
                    delog("disconnected user ", socket.userId, "deleted");
                }
            });
        });
        io = socketIO;
        module.exports.io = io;
    }
};

```

Explanation for above code: 

Each process subscribes to the message event. And when a process wants to emit a socket event it first publishes the event message via redis pub/sub, the process to which user whom we would like to send the socket emit to connected recevies the published message and sends it via socket.io connection. It was working like a charm until we increased number of events sent and received couple of days ago, and then we started getting the below error on our production servers that we could not reproduce on our side. We tried to debug the node_redis source code but could not figure out what was causing the issue. 

Each time an error occurs we also receive error on subscriber.on('error' event listener, but error parameter passed to function seems to be an empty object. Perhaps this may help you track the issue. We tried to enable debug_mode but logs were not helpful or there was not anything wrong. But we may provide it if you request it.

TypeError: Cannot read property 'callback' of undefined at normal_reply (C:\Forplay\forplay-web\ForplayNodeApp\node_modules\redis\index.js:722:27) at RedisClient.return_reply (C:\Forplay\forplay-web\ForplayNodeApp\node_modules\redis\index.js:824:9) at JavascriptRedisParser.returnReply (C:\Forplay\forplay-web\ForplayNodeApp\node_modules\redis\index.js:192:18) at JavascriptRedisParser.execute (C:\Forplay\forplay-web\ForplayNodeApp\node_modules\redis-parser\lib\parser.js:574:12) at TLSSocket. (C:\Forplay\forplay-web\ForplayNodeApp\node_modules\redis\index.js:274:27) at emitOne (events.js:96:13) at TLSSocket.emit (events.js:188:7)

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by ozerbdy** [comment]
Issue was related to the tls after all, nothing to do with node redis.
