### ISSUE TITLE
NPM test failing for node_redis

### ISSUE THREAD

**Issue by gdams** [NodeRedis/node_redis#1276]
When I run `npm test` I get the following error: 

```bash
 Error: Redis could not start on port 6379  
```

Do I need to setup my firewall for this to work?

**Comment by BridgeAR** [comment]
You already have a local redis instance running on that port. Right now it is not ideal that the tests rely an a specific port but it would be quite some work to change that. You just have to close your local instance and run the tests afterwards again.

**Comment by a-roberts** [comment]
Same for me, git clone this repo, `npm it`, I'm using node 8.9.0 and Docker.

```
docker pull redis
docker run -p 6379:6379 --name redis-server -d redis
npm test

> redis@2.8.0 test /home/aroberts/node_redis
> nyc --cache mocha ./test/*.js ./test/commands/*.js --timeout=8000

(node:3386) Warning: process.on(SIGPROF) is reserved while debugging


  1) "before all" hook
Error: Port 6379 is already in use. Tests can't start.

    at /home/aroberts/node_redis/test/lib/redis-process.js:37:23
    at tryCatcher (/home/aroberts/node_redis/node_modules/bluebird/js/release/util.js:16:23)
    at Holder$2._callFunction (eval at generateHolderClass (/home/aroberts/node_redis/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
    at Holder$2.checkFulfillment (eval at generateHolderClass (/home/aroberts/node_redis/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
    at Promise.eval (eval at thenCallback (/home/aroberts/node_redis/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
    at Promise._settlePromise (/home/aroberts/node_redis/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/home/aroberts/node_redis/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/aroberts/node_redis/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/aroberts/node_redis/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/aroberts/node_redis/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/aroberts/node_redis/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

------------------------|----------|----------|----------|----------|----------------|
File                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------|----------|----------|----------|----------|----------------|
All files               |    11.49 |     1.78 |     1.37 |    11.49 |                |
 node_redis             |    10.84 |     0.31 |        0 |    10.84 |                |
  index.js              |    10.84 |     0.31 |        0 |    10.84 |... 8,1084,1089 |
 node_redis/lib         |    11.99 |     2.92 |     2.33 |    11.99 |                |
  command.js            |    22.22 |       50 |        0 |    22.22 |... ,9,10,11,12 |
  commands.js           |    36.23 |    23.81 |       40 |    36.23 |... 101,104,105 |
  createClient.js       |     6.67 |        0 |        0 |     6.67 |... 71,75,76,79 |
  customErrors.js       |     37.5 |        0 |        0 |     37.5 |... 31,36,37,38 |
  debug.js              |       50 |        0 |        0 |       50 |            6,7 |
  extendedApi.js        |    13.85 |        0 |        0 |    13.85 |... 109,110,112 |
  individualCommands.js |     8.61 |        0 |        0 |     8.61 |... 613,615,616 |
  multi.js              |     6.42 |        0 |        0 |     6.42 |... 181,183,184 |
  utils.js              |     1.75 |        0 |        0 |     1.75 |... 117,118,120 |
------------------------|----------|----------|----------|----------|----------------|
npm ERR! Test failed.  See above for more details.
[aroberts@oc3752625144 node_redis]$ docker kill redis-server
redis-server
[aroberts@oc3752625144 node_redis]$ npm test

> redis@2.8.0 test /home/aroberts/node_redis
> nyc --cache mocha ./test/*.js ./test/commands/*.js --timeout=8000

(node:3586) Warning: process.on(SIGPROF) is reserved while debugging


  1) "before all" hook
Error: Redis could not start on port 6379

    at /home/aroberts/node_redis/test/lib/redis-process.js:40:23
    at tryCatcher (/home/aroberts/node_redis/node_modules/bluebird/js/release/util.js:16:23)
    at Holder$2._callFunction (eval at generateHolderClass (/home/aroberts/node_redis/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
    at Holder$2.checkFulfillment (eval at generateHolderClass (/home/aroberts/node_redis/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
    at Promise.eval (eval at thenCallback (/home/aroberts/node_redis/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
    at Promise._settlePromise (/home/aroberts/node_redis/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/home/aroberts/node_redis/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/aroberts/node_redis/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/aroberts/node_redis/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/aroberts/node_redis/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/aroberts/node_redis/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

------------------------|----------|----------|----------|----------|----------------|
File                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------|----------|----------|----------|----------|----------------|
All files               |    11.49 |     1.78 |     1.37 |    11.49 |                |
 node_redis             |    10.84 |     0.31 |        0 |    10.84 |                |
  index.js              |    10.84 |     0.31 |        0 |    10.84 |... 8,1084,1089 |
 node_redis/lib         |    11.99 |     2.92 |     2.33 |    11.99 |                |
  command.js            |    22.22 |       50 |        0 |    22.22 |... ,9,10,11,12 |
  commands.js           |    36.23 |    23.81 |       40 |    36.23 |... 101,104,105 |
  createClient.js       |     6.67 |        0 |        0 |     6.67 |... 71,75,76,79 |
  customErrors.js       |     37.5 |        0 |        0 |     37.5 |... 31,36,37,38 |
  debug.js              |       50 |        0 |        0 |       50 |            6,7 |
  extendedApi.js        |    13.85 |        0 |        0 |    13.85 |... 109,110,112 |
  individualCommands.js |     8.61 |        0 |        0 |     8.61 |... 613,615,616 |
  multi.js              |     6.42 |        0 |        0 |     6.42 |... 181,183,184 |
  utils.js              |     1.75 |        0 |        0 |     1.75 |... 117,118,120 |
------------------------|----------|----------|----------|----------|----------------|
npm ERR! Test failed.  See above for more details.
```

@BridgeAR hi, what's the recommended way to test node_redis then? Ideally with and without Docker - but with Docker (as at the very top of my post), it can't connect. Given how popular it is it'd be great to ensure it remains compatible with the latest Node.js releases.
