### ISSUE TITLE
ReplyError: ERR unknown command 'get'

### ISSUE THREAD

**Issue by GoToBoy** [NodeRedis/node_redis#1310]
node -v : v9.5.0
 "redis": "^2.8.0",

when using  client.get('key') , output 

```javascript
 ReplyError: ERR unknown command 'get'
    at parseError (/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/node_modules/redis-parser/lib/parser.js:303:14) command: 'GET', args: [ 'wxTicket' ], code: 'ERR' 

```

**Comment by GoToBoy** [comment]
also error on select command
```javascript
ERR unknown command 'select'
    at parseError (/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/node_modules/redis-parser/lib/parser.js:303:14) command: 'SELECT', args: [ 3 ], code: 'ERR' }

```

**Comment by GoToBoy** [comment]
find it happen was that redis using sentinel model ;  replace with normal model , would working right

**Comment by BridgeAR** [comment]
Hm, what do you mean with sentinel model?

**Comment by jybaek** [comment]
`sentinel mode` can not be used like `normal redis`. I think the approach was wrong.

**Comment by BridgeAR** [comment]
Closing as question.
