### ISSUE TITLE
Redis reply parser error: Error: saw 36 when expecting final CR

### ISSUE THREAD

**Issue by aahoughton** [NodeRedis/node_redis#135]
Not sure what to do with this; I have a relatively lightly loaded redis server (~300 - 400 requests per second, mostly small) and we're seeing this coming back from node_redis .. occasionally.   Decimal 36 == ASCII '$', which has meaning in the protocol but not at the end of a response from what I can see.

If this were a node_redis issue, I'd expect to see it far more often.  If it were a redis issue I'd expect to see it far more often.  As it is, I'm just lost.

Trace (this is from 0.5.11):

Error: Redis reply parser error: Error: saw 36 when expecting final CR
    at RedisReplyParser.execute (/home/aahoughton/node_modules/redis/lib/parser/javascript.js:217:35)
    at RedisClient.on_data (/home/aahoughton/node_modules/redis/index.js:328:27)
    at Socket.<anonymous> (/home/aahoughton/node_modules/redis/index.js:99:14)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:678:14)
    at IOWatcher.onReadable [as callback](net.js:177:10)
    at RedisReplyParser.<anonymous> (/home/aahoughton/node_modules/redis/index.js:91:28)
    at RedisReplyParser.emit (events.js:64:17)
    at RedisReplyParser.parser_error (/home/aahoughton/node_modules/redis/lib/parser/javascript.js:52:10)
    at RedisReplyParser.execute (/home/aahoughton/node_modules/redis/lib/parser/javascript.js:217:22)
    at RedisClient.on_data (/home/aahoughton/node_modules/redis/index.js:328:27)
    at Socket.<anonymous> (/home/aahoughton/node_modules/redis/index.js:99:14)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:678:14)
    at IOWatcher.onReadable [as callback](net.js:177:10)

**Comment by BridgeAR** [comment]
Fixed in newer versions
