### ISSUE TITLE
Hitting maxclients causes "Cannot read property 'error' of undefined"

### ISSUE THREAD

**Issue by qix** [NodeRedis/node_redis#1371]
* **Version**: redis: 4.0.11 node_redis 2.8.0
* **Platform**: Ubuntu 18.04 GCP
* **Description**: If you start a redis client with no_ready_check, the maxclients error from the redis server causes the client to emit a loop of bad error messages which are particularly nasty to try debug in production.

```
$ docker run -it -p 9379:6379 redis redis-server -- --maxclients 1
$ redis-cli -p 6379 # leave this one hanging
$ node
> var r = require('redis'); var c = r.createClient({ port: 9379, no_ready_check: true });
undefined
> TypeError: Cannot read property 'error' of undefined
    at RedisClient.return_error (.../node_modules/redis/index.js:687:21)
    at JavascriptRedisParser.returnError (.../node_modules/redis/index.js:196:18)
    at JavascriptRedisParser.execute (.../node_modules/redis-parser/lib/parser.js:572:12)
> TypeError: Cannot read property 'error' of undefined
    at RedisClient.return_error (.../node_modules/redis/index.js:687:21)
    at JavascriptRedisParser.returnError (.../node_modules/redis/index.js:196:18)
    at JavascriptRedisParser.execute (.../node_modules/redis-parser/lib/parser.js:572:12)
> TypeError: Cannot read property 'error' of undefined
    at RedisClient.return_error (.../node_modules/redis/index.js:687:21)
    at JavascriptRedisParser.returnError (.../node_modules/redis/index.js:196:18)
    at JavascriptRedisParser.execute (.../node_modules/redis-parser/lib/parser.js:572:12)
```

**Comment by qix** [comment]
(Note this might be related to #1274 but I'm not sure.)

**Comment by stockholmux** [comment]
Excellent catch!

**Comment by fancy-rabbit** [comment]
same problem
