### ISSUE TITLE
total_retry_time is not "time since last connect"

### ISSUE THREAD

**Issue by Meeeeow** [NodeRedis/node_redis#1421]
* **Version**: 2.8.0
* **Platform**: NodeJS 11.12 on Windows 10
* **Description**: 
total_retry_time is not "time since last connect", it's just total time of waiting for retry, time from connect to timeout was ignored.

Here is my log with real time and time passed to retry_strategy:
```
{"name":"App","hostname":"Desktop","pid":28432,"level":50,"msg":"[RedisClient] Redis losted connection, time since last connect: 0 { attempt: 1,\n  error:\n   { Error: Redis connection to redis:6379 failed - connect ETIMEDOUT 192.168.31.25:6379\n       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)\n     errno: 'ETIMEDOUT',\n     code: 'ETIMEDOUT',\n     syscall: 'connect',\n     address: '192.168.31.25',\n     port: 6379 },\n  total_retry_time: 0,\n  times_connected: 0 }","time":"2019-03-18T08:25:38.402Z","v":0}
{"name":"App","hostname":"Desktop","pid":28432,"level":50,"msg":"[RedisClient] Redis losted connection, time since last connect: 10 { attempt: 2,\n  error:\n   { Error: Redis connection to redis:6379 failed - connect ETIMEDOUT 192.168.31.25:6379\n       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)\n     errno: 'ETIMEDOUT',\n     code: 'ETIMEDOUT',\n     syscall: 'connect',\n     address: '192.168.31.25',\n     port: 6379 },\n  total_retry_time: 10,\n  times_connected: 0 }","time":"2019-03-18T08:25:59.424Z","v":0}
{"name":"App","hostname":"Desktop","pid":28432,"level":50,"msg":"[RedisClient] Redis losted connection, time since last connect: 20 { attempt: 3,\n  error:\n   { Error: Redis connection to redis:6379 failed - connect ETIMEDOUT 192.168.31.25:6379\n       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)\n     errno: 'ETIMEDOUT',\n     code: 'ETIMEDOUT',\n     syscall: 'connect',\n     address: '192.168.31.25',\n     port: 6379 },\n  total_retry_time: 20,\n  times_connected: 0 }","time":"2019-03-18T08:26:20.448Z","v":0}
{"name":"App","hostname":"Desktop","pid":28432,"level":50,"msg":"[RedisClient] Redis losted connection, time since last connect: 30 { attempt: 4,\n  error:\n   { Error: Redis connection to redis:6379 failed - connect ETIMEDOUT 192.168.31.25:6379\n       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)\n     errno: 'ETIMEDOUT',\n     code: 'ETIMEDOUT',\n     syscall: 'connect',\n     address: '192.168.31.25',\n     port: 6379 },\n  total_retry_time: 30,\n  times_connected: 0 }","time":"2019-03-18T08:26:41.469Z","v":0}
```
The documents says it's milliseconds since last connect, but when the callback called with "total_retry_time: 30", 1 minutes was passed...

**Comment by knoxcard** [comment]
Seems there is a bunch of problems with reconnecting as of late.  Something was messed up.

**Comment by JamesMGreene** [comment]
This might be a viable workaround if you're using `retry_strategy`: 🤔 

```js
const client = Redis.createClient({
  retry_strategy: function (retry_params) {
    const totalRetryTime = (Date.now() - this.lastDisconnected) || this.total_retry_time
    retry_params.total_retry_time = totalRetryTime
    this.retry_totaltime = totalRetryTime
    
    // Do your normal `retry_strategy` calculations here...
  }
})
client.on('end', function () { this.lastDisconnected = Date.now() })
```
