### ISSUE TITLE
Cannot find Endpoint while using sentinel

### ISSUE THREAD

**Issue by Yosafat1997** [NodeRedis/node_redis#1445]
* **Version**: 2.8.0 for Node Redis and 0.3.3 for redis-sentinel
* **Platform**: Nodejs v10.15.2 run in Ubuntu
* **Description**: 

I have project that connect my cloud function into redis that run in google VM. As requirement, I implement sentinel server with only two server (due that only two server are available for me rn). When i have run the function, this is the error that i have:

```
Error: Failed to find a sentinel from the endpoints
    at /srv/node_modules/redis-sentinel/index.js:227:18
    at tryCatchReject (/srv/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/srv/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/srv/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/srv/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/srv/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/srv/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```
This is my redis config on the function
```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
const redis = require("redis");
const sentinel = require('redis-sentinel');
var endpoints = [
    {host: 'dev-redis-0', port: 26379},
    {host: 'dev-redis-1', port: 26379}
];
 
var opts = {}; // Standard node_redis client options
var masterName = 'mymaster';
const bbkey             = "outlet:1:available_vehicles:bluebird"
const	sbkey             = "outlet:1:available_vehicles:silverbird"
var redisClient = sentinel.createClient(endpoints, masterName, opts);
// client.on("error",function(err){
//     console.log("ERROR"+err);
// });
var Sentinel = sentinel.Sentinel(endpoints);
var masterClient = sentinel.createClient(endpoints, masterName, {role: 'master'}); 
var slaveClient = sentinel.createClient(endpoints, masterName, {role: 'slave'});
var sentinelClient = sentinel.createClient(endpoints, {role: 'sentinel'});
and this is my connection config on index.js

...
```
I 'm still new using Redis and NodeRedis, and any helps are appreciated. Thank You

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by stockholmux** [comment]
Looks like this a problem with the (redis-sentinel)[https://www.npmjs.com/package/redis-sentinel] package. (In fact, just glancing at it, I don't believe you're using this module at all). You should take the issue to that module.

I'm going to close this issue.

**Comment by doerme** [comment]
haha, redis had not be used
