### ISSUE TITLE
ReplyError: ERR invalid longitude,latitude pair 37.779872,-122.282185

### ISSUE THREAD

**Issue by laerciokonzen** [NodeRedis/node_redis#1465]
* **Version**:  2.8.0
* **Platform**: Node.js v8.11.3 on Windows 10
* **Description**: When I try to use geoadd with the bellow lat and lng I get the **ReplyError**

```js
geoadd('placesList', 37.779872,-122.282185, 'item data');
```
``` log
events.js:183
      throw er; // Unhandled 'error' event
      ^
ReplyError: ERR invalid longitude,latitude pair 37.779872,-122.282185
    at parseError (C:\projetos\places-autocomplete\node_modules\redis-parser\lib\parser.js:193:12)    
    at parseType (C:\projetos\places-autocomplete\node_modules\redis-parser\lib\parser.js:303:14)  
```

**Comment by stockholmux** [comment]
This is an error from redis itself. As per the GEOADD documentation:
```
Valid longitudes are from -180 to 180 degrees.
Valid latitudes are from -85.05112878 to 85.05112878 degrees.
```
Your coordinates are out of range.
