### ISSUE TITLE
node_redis: Couldn't get Redis connection after 1 attempts

### ISSUE THREAD

**Issue by atrun** [NodeRedis/node_redis#208]
console show “node_redis: Couldn't get Redis connection after 1 attempts”，client willn't not connection Redis

   error: Redis connection to 192.168.80.92:6379 failed - This socket is closed.
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Cannot call method 'toString' of undefined
    at Command.callback (/home/hadoop/redis/sreeix-redis-proxy/server.js:21:24)
    at RedisClient.flush_and_error (/home/hadoop/redis/sreeix-redis-proxy/node_modules/redis/index.js:113:25)
    at RedisClient.on_error (/home/hadoop/redis/sreeix-redis-proxy/node_modules/redis/index.js:131:10)
    at Socket.<anonymous> (/home/hadoop/redis/sreeix-redis-proxy/node_modules/redis/index.js:70:14)
    at Socket.emit (events.js:67:17)
    at Array.0 (net.js:301:14)
    at EventEmitter._tickCallback (node.js:192:40)

Thanks.

**Comment by gormargaryan** [comment]
> Is redis running, and on that port? (test using redis-cli).
> 
> Also, make sure to add this listener so you can see the error event.
> If there is still trouble, please add information on what the error event emits.
> 
> Thanks,
> D
> 
> ```js
> var redis = require("redis"),
>     client = redis.createClient();
> 
> client.on("error", function (err) {
>     console.log("Error " + err);
> });
> ```

I get the same error((
