### ISSUE TITLE
4.1.0 publish breaks when publishing an integer

### ISSUE THREAD

**Issue by anshul-kai** [NodeRedis/node_redis#2116]
This was working fine up until 4.0.6 but starting in version 4.1.0, publishing integers throws the following error.

```
/node_modules/@redis/client/dist/lib/client/RESP2/encoder.js:20
            throw new TypeError('Invalid argument type');
                  ^

TypeError: Invalid argument type
    at encodeCommand (/node_modules/@redis/client/dist/lib/client/RESP2/encoder.js:20:19)
    at RedisCommandsQueue.getCommandToSend (/node_modules/@redis/client/dist/lib/client/commands-queue.js:187:45)
    at Commander._RedisClient_tick (/node_modules/@redis/client/dist/lib/client/index.js:429:76)
    at Commander._RedisClient_sendCommand (/node_modules/@redis/client/dist/lib/client/index.js:413:82)
    at Commander.commandsExecutor (/node_modules/@redis/client/dist/lib/client/index.js:167:154)
    at Commander.BaseClass.<computed> [as publish] (/node_modules/@redis/client/dist/lib/commander.js:8:29)
```

**Environment:**
 - **Node.js Version**: 16
 - **Redis Server Version**: 4
 - **Node Redis Version**: 4.1.0
 - **Platform**: Ubuntu

**Comment by leibale** [comment]
@a-koka @byron70 in previous versions (4.0.0-4.0.6) some values were incorrectly converted into strings, which could cause unexpected behaviors (see #1898 for example).

**Comment by patel-kalp** [comment]
I am currently on 4.1.0 and facing the same issue @leibale

**Comment by a-koka** [comment]
I'm not sure if I follow this thoroughly. Publishing integer values has worked for the longest time until 4.1.0. Are we saying that publishing integers is no longer supported?

`redisPubClient.publish('channel', 1)` used to work but now has to be written as `redisPubClient.publish('channel', '1')`

**Comment by tugtugtug** [comment]
@leibale this is definitely a regression, the `addCommand` is also now broken with integer/boolean values. If https://github.com/redis/node-redis/issues/1898 complains about converting `undefined`, `null` to emtpy strings, shouldn't that particular error be fixed instead of completely stop conversion of any non-buffer, non-string arguments?

**Comment by patel-kalp** [comment]
```
import * as redis from 'redis';
import session from 'express-session';
import connectRedis from 'connect-redis';

const RedisStore = connectRedis(session);
const redisClient = redis.createClient();
await redisClient.connect();

app.use(
        session({
            name: 'qid',
            store: new RedisStore({
                client: redisClient as any,
                disableTouch: true,
            }),
            cookie: {
                maxAge: 31536000000,
                sameSite: "lax",
                secure: false
            },
            saveUninitialized: false,
            secret: "test",
            resave: false
        })
)
```
I am not sure if I am doing this right, but something similar has worked for me before. So now should I be making maxAge a string? @leibale

**Comment by moisesbites** [comment]
In this version 4.1.0, Date values are not working anymore too . Before, they worked fine.

**Comment by moisesbites** [comment]
Hi, some solution for this issue?

**Comment by musta20** [comment]
hi facing the same issue solution yet

**Comment by younggeun0** [comment]
It works for me adding createClient option(`legecyMode: true`) and connect without `await`. 

```javascript
import connectRedis from "connect-redis";
...
    const redisClient = createClient({
        legacyMode: true,
    });
   redisClient.connect();
```

**Comment by moisesbites** [comment]
> I got the same error. It works for me adding createClient option(`legecyMode: true`) and `connect()` together.
> 
> ```js
> import connectRedis from "connect-redis";
> ...
>     const redisClient = createClient({
>         legacyMode: true,
>     });
>    await redisClient.connect();
> ```

For me, this workaround it's not working... I use many resources from v4.

**Comment by dragonlobster** [comment]
please help my production is broken because of this update

**Comment by moisesbites** [comment]
> please help my production is broken because of this update

@dragonlobster for while, convert to string every value on or before command db.set... when you to execute command get, convert do correct datatype from string...

**Comment by devel0perx** [comment]
@a-koka i am using redis 7 and node 16 having same problem but it work sometime and give above error What to do ?

**Comment by leibale** [comment]
Make sure to convert the channel and message into strings or buffers

**Comment by zelucena** [comment]
I found the same issue while trying to upgrade [Node ACL2](https://github.com/flash-oss/node_acl) to Redis 4.3.0.
`sAdd` stopped working with integers as well.
Stack trace:
```
 Uncaught TypeError: Invalid argument type
      at encodeCommand (node_modules\@redis\client\dist\lib\client\RESP2\encoder.js:17:19)
      at RedisCommandsQueue.getCommandToSend (node_modules\@redis\client\dist\lib\client\commands-queue.js:187:45)
      at Commander._RedisClient_tick (node_modules\@redis\client\dist\lib\client\index.js:440:76)
      at Commander.multiExecutor (node_modules\@redis\client\dist\lib\client\index.js:246:86)
      at Commander.exec (node_modules\@redis\client\dist\lib\client\multi-command.js:84:175)
      at RedisBackend.end (lib\redis-backend.js:36:46)
      at RedisBackend.tryCatcher (node_modules\bluebird\js\release\util.js:16:23)
      at RedisBackend.ret [as endAsync] (eval at makeNodePromisifiedEval (node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
      at Acl.allow (lib\acl.js:337:29)
      at C:\Users\jose.lucena\Downloads\node_acl-master\node_acl-master\lib\acl.js:766:59
      at tryCatcher (node_modules\bluebird\js\release\util.js:16:23)
      at Object.gotValue (node_modules\bluebird\js\release\reduce.js:168:18)
      at Object.gotAccum (node_modules\bluebird\js\release\reduce.js:155:25)
      at Object.tryCatcher (node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (node_modules\bluebird\js\release\promise.js:673:18)
      at C:\Users\jose.lucena\Downloads\node_acl-master\node_acl-master\node_modules\bluebird\js\release\nodeback.js:42:21
      at RedisBackend.end (lib\redis-backend.js:37:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by moisesbites** [comment]
> I found the same issue while trying to upgrade [Node ACL2](https://github.com/flash-oss/node_acl) to Redis 4.3.0.
> `sAdd` stopped working with integers as well.
> Stack trace:
> ```
>  Uncaught TypeError: Invalid argument type
>       at encodeCommand (node_modules\@redis\client\dist\lib\client\RESP2\encoder.js:17:19)
>       at RedisCommandsQueue.getCommandToSend (node_modules\@redis\client\dist\lib\client\commands-queue.js:187:45)
>       at Commander._RedisClient_tick (node_modules\@redis\client\dist\lib\client\index.js:440:76)
>       at Commander.multiExecutor (node_modules\@redis\client\dist\lib\client\index.js:246:86)
>       at Commander.exec (node_modules\@redis\client\dist\lib\client\multi-command.js:84:175)
>       at RedisBackend.end (lib\redis-backend.js:36:46)
>       at RedisBackend.tryCatcher (node_modules\bluebird\js\release\util.js:16:23)
>       at RedisBackend.ret [as endAsync] (eval at makeNodePromisifiedEval (node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
>       at Acl.allow (lib\acl.js:337:29)
>       at C:\Users\jose.lucena\Downloads\node_acl-master\node_acl-master\lib\acl.js:766:59
>       at tryCatcher (node_modules\bluebird\js\release\util.js:16:23)
>       at Object.gotValue (node_modules\bluebird\js\release\reduce.js:168:18)
>       at Object.gotAccum (node_modules\bluebird\js\release\reduce.js:155:25)
>       at Object.tryCatcher (node_modules\bluebird\js\release\util.js:16:23)
>       at Promise._settlePromiseFromHandler (node_modules\bluebird\js\release\promise.js:547:31)
>       at Promise._settlePromise (node_modules\bluebird\js\release\promise.js:604:18)
>       at Promise._settlePromise0 (node_modules\bluebird\js\release\promise.js:649:10)
>       at Promise._settlePromises (node_modules\bluebird\js\release\promise.js:729:18)
>       at Promise._fulfill (node_modules\bluebird\js\release\promise.js:673:18)
>       at C:\Users\jose.lucena\Downloads\node_acl-master\node_acl-master\node_modules\bluebird\js\release\nodeback.js:42:21
>       at RedisBackend.end (lib\redis-backend.js:37:13)
>       at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```
> 

Convert to string before send to redis client, reconvert to datatype after get from redis. It's the solution, for while.

**Comment by DDDDDanica** [comment]
> I got the same error. It works for me adding createClient option(`legecyMode: true`) and `connect()` together.
> 
> ```js
> import connectRedis from "connect-redis";
> ...
>     const redisClient = createClient({
>         legacyMode: true,
>     });
>    await redisClient.connect();
> ```

Thank you !!! and this should be the fix and `connect-redis` did not support redis@v4 completely.

https://github.com/tj/connect-redis

```
Known compatible and tested clients:

[redis](https://github.com/NodeRedis/node-redis) (v3, v4 with legacyMode: true)
[ioredis](https://github.com/luin/ioredis)
[redis-mock](https://github.com/yeahoffline/redis-mock) for testing.
```

It would be great if this is specified in migration guide ~

**Comment by kasvith** [comment]
This is a serious error :(
