### ISSUE TITLE
ERR wrong number of arguments for 'hmset' command

### ISSUE THREAD

**Issue by yuri-karadzhov** [NodeRedis/node_redis#262]
after npm update the problem appear with node-redis

node_redis: no callback to send error: Error: ERR wrong number of arguments for 'hmset' command

/var/www/node_modules/redis/index.js:475
            throw err;
                  ^
Error: Error: ERR wrong number of arguments for 'hmset' command
    at HiredisReplyParser.RedisClient.init_parser (/var/www/node_modules/redis/index.js:253:27)
    at HiredisReplyParser.EventEmitter.emit (events.js:88:17)
    at HiredisReplyParser.execute (/var/www/node_modules/redis/lib/parser/hiredis.js:41:18)
    at RedisClient.on_data (/var/www/node_modules/redis/index.js:440:27)
    at Socket.<anonymous> (/var/www/node_modules/redis/index.js:70:14)
    at Socket.EventEmitter.emit (events.js:88:17)
    at TCP.onread (net.js:395:14)

I have node 0.8.8 and npm 1.1.59

**Comment by aer123456** [comment]
你的某一个变量名或者函数的参数名与库发生冲突了，建议该参数名就好了。 我刚刚也遇到这个问题。

**Comment by BridgeAR** [comment]
This is fixed in newer versions.

**Comment by tengwang0318** [comment]
> 你的某一个变量名或者函数的参数名与库发生冲突了，建议该参数名就好了。 我刚刚也遇到这个问题。

别说中文（don't speak Chinese in Github
