### ISSUE TITLE
Cannot find module '@redis/client/lib/commands/generic-transformers

### ISSUE THREAD

**Issue by Djay77** [NodeRedis/node_redis#2871]
### Description

Hello,

I tried to use the sentinel mode in version 5.0.0-next.5 but I have a problem with this error when I use the createSentinel from @redis/client.

I'm in a Next.js project and I have a custom cache handler to use Redis

`const { createSentinel } = require('@redis/client');`

But, I have an error : "Cannot find module '@redis/client/**lib**/commands/generic-transformers"

There are not **lib** folder in my node_modules for @redis/client. The lib folder is IN the dist/

<img width="1379" alt="image" src="https://github.com/user-attachments/assets/ff9b5d9f-7f19-4a10-aefb-4dd9c76b5881">

Is it en error or I don't call correctly the createSentinel ?

Thanks

### Node.js Version

20.15.1

### Platform

Kubernetes

### Logs

```bash
⨯ Error: Cannot find module '@redis/client/lib/commands/generic-transformers'
Require stack:
- /app/node_modules/@redis/search/dist/lib/commands/CREATE.js
- /app/node_modules/@redis/search/dist/lib/commands/ALTER.js
- /app/node_modules/@redis/search/dist/lib/commands/index.js
- /app/node_modules/@redis/search/dist/lib/index.js
- /app/node_modules/redis/dist/index.js
- /app/node_modules/@neshca/cache-handler/dist/handlers/redis-stack.cjs
- /app/cache-handler.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at /app/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at mod.require (/app/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/app/node_modules/@redis/search/dist/lib/commands/CREATE.js:4:32)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/@redis/search/dist/lib/commands/CREATE.js',
    '/app/node_modules/@redis/search/dist/lib/commands/ALTER.js',
    '/app/node_modules/@redis/search/dist/lib/commands/index.js',
    '/app/node_modules/@redis/search/dist/lib/index.js',
    '/app/node_modules/redis/dist/index.js',
    '/app/node_modules/@neshca/cache-handler/dist/handlers/redis-stack.cjs',
    '/app/cache-handler.cjs'
  ]
}
```

**Comment by tonywangcn** [comment]
same here, did U solve this issue ? @Djay77
