### ISSUE TITLE
web_server.js: Cannot find module 'redis'

### ISSUE THREAD

**Issue by peepo** [NodeRedis/node_redis#37]
node v0.3 
  redis v2.2 antirez git

  wfm most test.js

 at resolveModuleFilename (node.js:265:13)
    at loadModule (node.js:231:20)
    at require (node.js:291:14)
    at Object.<anonymous> (/Users/jaymini/node_redis/examples/web_server.js:4:20)
    at Module._compile (node.js:348:23)
    at Object..js (node.js:356:12)
    at Module.load (node.js:279:25)
    at Array.<anonymous> (node.js:370:24)
    at EventEmitter._tickCallback (node.js:42:22)
    at node.js:634:9

**Comment by shafwanaw** [comment]
after I enter the command node server.js to make localhost, after I stabbed the command it comes out immediately


-------------------------------------Starting server----------------------------------------------------
2019-10-12T08:09:36.456Z - error: Certificate file or key file is missing, falling back to non-SSL mode
2019-10-12T08:09:36.460Z - error: To create them, simply run the following from your shell: sh ./scripts/generate-ssl-certs.sh 

internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module 'redis-server'
Require stack:
- /etc/magoware/config/lib/redis.js
- /etc/magoware/modules/mago/server/policies/mago.server.policy.js
- /etc/magoware/config/lib/express.js
- /etc/magoware/config/lib/app.js
- /etc/magoware/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/etc/magoware/config/lib/redis.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/etc/magoware/modules/mago/server/policies/mago.server.policy.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/etc/magoware/config/lib/redis.js',
    '/etc/magoware/modules/mago/server/policies/mago.server.policy.js',
    '/etc/magoware/config/lib/express.js',
    '/etc/magoware/config/lib/app.js',
    '/etc/magoware/server.js'
  ]
}
