### ISSUE TITLE
auth error message is bad

### ISSUE THREAD

**Issue by lookfirst** [NodeRedis/node_redis#392]
index.js, around line 171:

```
return self.emit("error", new Error("Auth error: " + err.message));
```

Should just be:

```
return self.emit("error", new Error("Auth error: " + err));
```

stacktrace:

```
Error: Auth error: undefined
    at Command.RedisClient.do_auth.self.send_anyway [as callback] (/app/node_modules/redis/index.js:171:43)
    at RedisClient.flush_and_error (/app/node_modules/redis/index.js:126:25)
    at RedisClient.connection_gone (/app/node_modules/redis/index.js:421:10)
    at Socket.<anonymous> (/app/node_modules/redis/index.js:91:14)
    at Socket.EventEmitter.emit (events.js:93:17)
    at TCP.onread (net.js:418:51)
```

**Comment by BridgeAR** [comment]
Fixed in newer versions
