### ISSUE TITLE
Handling of redis disconnects

### ISSUE THREAD

**Issue by thanpolas** [NodeRedis/node_redis#413]
I was fiddling in node console, playing with blocking [blpop](http://redis.io/commands/blpop). 

I experimented by shutting down the redis server while the blocking pop command was running... The result was quite interesting as the callback was called over 15 times...

Is there a way to handle this more gracefully?

Here's the paste from my console
```
> r.blpop('que1', 'que2',10, function(){console.log('blpop', arguments)});
true
> { '0': 'Redis connection gone from end event.' }
{ '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
rpop { '0': 'Redis connection gone from end event.' }
rpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }
blpop { '0': 'Redis connection gone from end event.' }

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (**/node_modules/redis/index.js:151:24)
    at Socket.<anonymous> (**/node_modules/redis/index.js:86:14)
    at Socket.EventEmitter.emit (events.js:96:17)
    at Socket._destroy.self.errorEmitted (net.js:329:14)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

**Comment by BridgeAR** [comment]
This is fixed in newer versions (should be since v.2.0).
