### ISSUE TITLE
"no callback to send error", but there is!

### ISSUE THREAD

**Issue by christiangenco** [NodeRedis/node_redis#454]
Here's my code:
```coffeescript
try
  redis = require('redis')
catch
  console.log "redis errored"
client = redis.createClient(6011, "127.0.0.1",connect_timeout: 10000)
client.on "error", (e) ->
  console.log "oops; redis doesn't work"
  console.log e
client.on "connect", ->
  console.log "redis connected"
  redisConnected = true
  client.set 'foo', 'bar', (err, reply) -> 
    console.log reply
    client.expire('foo', 3)
```

And here's what I'm getting:

    info  - socket.io started
    created redis object...
    redis connected
    undefined
    node_redis: no callback to send error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

    /home/node/PROJECT/shared/node_modules/redis/index.js:523
                throw err;
                      ^
    Error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
        at ReplyParser.RedisClient.init_parser (/home/node/PROJECT/shared/node_modules/redis/index.js:263:27)
        at ReplyParser.EventEmitter.emit (events.js:96:17)
        at ReplyParser.send_error (/home/node/PROJECT/shared/node_modules/redis/lib/parser/javascript.js:296:10)
        at ReplyParser.execute (/home/node/PROJECT/shared/node_modules/redis/lib/parser/javascript.js:181:22)
        at RedisClient.on_data (/home/node/PROJECT/shared/node_modules/redis/index.js:488:27)
        at Socket.<anonymous> (/home/node/PROJECT/shared/node_modules/redis/index.js:82:14)
        at Socket.EventEmitter.emit (events.js:96:17)
        at TCP.onread (net.js:397:14)

Granted, this is caused by a misconfiguration of redis, but `node_redis` shouldn't crash my server D:

**Comment by BridgeAR** [comment]
This should be fixed in newer versions. This ticket is ancient but it would still be nice if you could verify that @christiangenco
