### ISSUE TITLE
how connect to twemproxy

### ISSUE THREAD

**Issue by jimsproject** [NodeRedis/node_redis#487]
Dear all,

is it possible  connect node to twemproxy?
note: i have success connect using php, and redis-cli.

thank you

jimmy 

my testing script:
var redis = require("../../libs/node_modules/redis");
client = redis.createClient("22121", "192.168.1.6");

err:
/var/www/dev/libs/node_modules/redis/index.js:139
                    throw callback_err;
                          ^
Error: Ready check failed: undefined
    at RedisClient.on_info_cmd (/var/www/dev/libs/node_modules/redis/index.js:341:35)
    at Command.callback (/var/www/dev/libs/node_modules/redis/index.js:389:14)
    at RedisClient.flush_and_error (/var/www/dev/libs/node_modules/redis/index.js:136:29)
    at RedisClient.connection_gone (/var/www/dev/libs/node_modules/redis/index.js:445:10)
    at Socket.<anonymous> (/var/www/dev/libs/node_modules/redis/index.js:94:14)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)

**Comment by BridgeAR** [comment]
Reference #704

**Comment by jackwoods** [comment]
Not working again, no such option anymore
