### ISSUE TITLE
Subscribing & unsubscribing to multiple channels crashes client 

### ISSUE THREAD

**Issue by josephg** [NodeRedis/node_redis#577]
Using `redis@0.10.1`, this code:

```javascript
var redis = require('redis');
var client = redis.createClient();

client.subscribe('one', 'two', 'three', function(err) {});
client.unsubscribe('one', 'two', 'three', function(err) {});
client.subscribe('fsad', 'fdssfd', 'fdssdf', function(err) {});
```

... Causes this crash:

```
$ node test.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: node_redis command queue state error. If you can reproduce this, please report it.
  at RedisClient.return_reply (/Users/josephg/src/rediscrash/node_modules/redis/index.js:705:15)
  at ReplyParser.<anonymous> (/Users/josephg/src/rediscrash/node_modules/redis/index.js:309:14)
  at ReplyParser.EventEmitter.emit (events.js:95:17)
  at ReplyParser.send_reply (/Users/josephg/src/rediscrash/node_modules/redis/lib/parser/javascript.js:300:10)
  at ReplyParser.execute (/Users/josephg/src/rediscrash/node_modules/redis/lib/parser/javascript.js:211:22)
  at RedisClient.on_data (/Users/josephg/src/rediscrash/node_modules/redis/index.js:534:27)
```

It has something to do with redis replying with multiple responses, which confuses the command queue. I can work around it by only subscribing & unsubscribing to one item at a time.

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
@josephg @wbotelhos could you have a look at #857 ? :)

**Comment by wbotelhos** [comment]
I'm sorry @BridgeAR , I can't.
I'm currently in another company. :disappointed:

**Comment by BridgeAR** [comment]
This is finally fixed on master
