### ISSUE TITLE
Command Queue Stack Error

### ISSUE THREAD

**Issue by ghost** [NodeRedis/node_redis#603]
I'm trying to `SUBSCRIBE`/`UNSUBSCRIBE` from channels in the following way (minimal working example):

```
var client = require('redis').createClient();

function subscribe(channels) {
    client.unsubscribe(function (error) {
        console.log(error);
    });
    client.subscribe(channels, function (error) {
        console.log(error);
    });
}

subscribe(['1', '3']);
subscribe(['2']);
```

The idea is, at any moment, completely replace this list of subscribed channels with a different one. This immediately causes the following error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: node_redis command queue state error. If you can reproduce this, please report it.
    at RedisClient.return_reply (/myproject/node_modules/redis/index.js:705:15)
    at HiredisReplyParser.RedisClient.init_parser (/myproject/node_modules/redis/index.js:309:14)
    at HiredisReplyParser.emit (events.js:95:17)
    at HiredisReplyParser.execute (/myproject/node_modules/redis/lib/parser/hiredis.js:43:18)
    at RedisClient.on_data (/myproject/node_modules/redis/index.js:534:27)
    at Socket.stream.on.self.should_buffer (/myproject/node_modules/redis/index.js:91:14)
    at Socket.emit (events.js:95:17)
    at Socket.stream.pause.paused (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
```

Making the call to `client.subscribe` inside the callback passed to `client.unsubscribe` instead doesn't help. Wrapping the call to `client.subscribe` with `process.nextTick` seems to provide a workaround the problem. Any clues on how to solve this?

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
Reopening this as it is not yet resolved and seems to be a major issue

**Comment by BridgeAR** [comment]
@bmcustodio @rootslab could you have a look at #857 ? :)

**Comment by BridgeAR** [comment]
This is finally fixed on master.
