### ISSUE TITLE
error upgrading from 0.10.1 to 0.10.2

### ISSUE THREAD

**Issue by fabriziomoscon** [NodeRedis/node_redis#618]
Even though most probably I could have some *strange* DB index on redis I think this error should not happen:
```
Error: ERR invalid DB index
      at ReplyParser.<anonymous> (/home/fabrizio/projects/arco/node_modules/redis/index.js:305:31)
      at ReplyParser.EventEmitter.emit (events.js:95:17)
      at ReplyParser.send_error (/home/fabrizio/projects/arco/node_modules/redis/lib/parser/javascript.js:296:10)
      at ReplyParser.execute (/home/fabrizio/projects/arco/node_modules/redis/lib/parser/javascript.js:181:22)
      at RedisClient.on_data (/home/fabrizio/projects/arco/node_modules/redis/index.js:534:27)
      at Socket.<anonymous> (/home/fabrizio/projects/arco/node_modules/redis/index.js:91:14)
      at Socket.EventEmitter.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:746:14)
      at Socket.EventEmitter.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:408:10)
      at emitReadable (_stream_readable.js:404:5)
      at readableAddChunk (_stream_readable.js:165:9)
      at Socket.Readable.push (_stream_readable.js:127:10)
      at TCP.onread (net.js:526:21)
```

the diff is minimal and should not have any impact, but in practice it crashes my server. 

node: `v0.10.17`
My redis-server: `Redis server v=2.8.4 sha=00000000:0 malloc=jemalloc-3.4.1 bits=64 build=a44a05d76f06a5d9`
I am on `Linux fab 3.13.0-27-generic #50-Ubuntu SMP Thu May 15 18:06:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ianjuma** [comment]
@fabriziomoscon  same error, anything new on this? a version incompatibility issue?

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.

**Comment by BridgeAR** [comment]
@fabriziomoscon @kbjr @ianjuma what did you do that this error occurred? The error itself is thrown by redis, so node_redis is only parsing what is returned by redis itself.

**Comment by BridgeAR** [comment]
If anyone still runs into this issue, please let me know. I checked the commits between 0.10.1 and 0.10.2 and could not find anything that would result in such a behavior. This is likely coming from another source than that version bump.
