### ISSUE TITLE
Error occured when the internal send_command function was called without the 'args' parameter.

### ISSUE THREAD

**Issue by dreamlover** [NodeRedis/node_redis#629]
In the "client.send_command(command_name, args, callback)" section of the read me, it says "
All commands are sent as multi-bulk commands. args can either be an Array of arguments, or omitted. ". But when I call that function with the args really omitted, I got the following error: 
---------------------------------
        throw new Error("send_command: second argument must be an array");
              ^
Error: send_command: second argument must be an array
    at RedisClient.send_command (e:\Work\SGLM\Server\GameServer\SRC\node_modules\redis\index.js:771:15)
    at Object._stopServer [as stopServer] (e:\Work\SGLM\Server\GameServer\SRC\data\redis.js:27:8)
    at Object._stopServer [as stopServer] (e:\Work\SGLM\Server\GameServer\SRC\data\portal.js:12:11)
    at Array.2 (e:\Work\SGLM\Server\GameServer\SRC\sglm.js:49:37)
    at ReadStream.__onData (e:\Work\SGLM\Server\GameServer\SRC\common\CConsoleCommand.js:63:19)
    at ReadStream.EventEmitter.emit (events.js:95:17)
    at ReadStream.<anonymous> (_stream_readable.js:745:14)
    at ReadStream.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:407:10)
    at emitReadable (_stream_readable.js:403:5)

**Comment by blainsmith** [comment]
In order to better support this project and its new group of collaborators under a new org we are trying to clean up and close issues older than 6 months. Your issue may have been fixed since the issue was open, however, if you are still experiencing a problem **please** re-open this issue and we will label it accordingly.
