### ISSUE TITLE
JXCore compilation

### ISSUE THREAD

**Issue by delagen** [NodeRedis/node_redis#664]
```
Caught exception: undefined is not a function
 Stack: TypeError: undefined is not a function
    at HiredisReplyParser.reset (...\node_module
s\redis\lib\parser\hiredis.js.jx:21:19)
    at new HiredisReplyParser (...\node_modules\
redis\lib\parser\hiredis.js.jx:12:10)
    at RedisClient.init_parser (...\node_modules
\redis\index.js.jx:309:25)
    at RedisClient.on_connect (...\node_modules\
redis\index.js.jx:267:10)
    at Socket.<anonymous> (...\node_modules\redi
s\index.js.jx:99:14)
    at Socket.emit (events.js:117:20)
    at Object.afterConnect [as oncomplete] (net.js:900:10)
    at process.__makeCall (node.js:420:23)
```

**Comment by chanakyapleasehorn** [comment]
Hey I am also seeing same error. Can you help me where should I change this parser to javascript, I mean in which file.

Thanks in advance.
