### ISSUE TITLE
node_redis: no callback to send error: ERR syntax error

### ISSUE THREAD

**Issue by mavrick** [NodeRedis/node_redis#755]
node_redis: no callback to send error: ERR syntax error
Fri, 22 May 2015 14:13:32 GMT uncaughtException: ERR syntax error
Error: ERR syntax error
    at ReplyParser.<anonymous> (C:\app\node_modules\redis\index.js:317:31)
    at ReplyParser.emit (events.js:95:17)
    at ReplyParser.send_error (C:\app\node_modules\redis\lib\parser\javascript.js:296:10)
    at ReplyParser.execute (C:\app\node_modules\redis\lib\parser\javascript.js:181:22)
    at RedisClient.on_data (C:\app\node_modules\redis\index.js:547:27)
    at Socket.<anonymous> (C:\app\node_modules\redis\index.js:102:14)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
worker 15080 died (1). restarting...

```javascript
var redis = require("redis");
global.redisClient = redis.createClient(config.redis.port, config.redis.host, {auth_pass: config.redis.pass});
redisClient.get(hash, function(err, data) { ... });
```

**Comment by blainsmith** [comment]
Are you still experiencing this error?

**Comment by BridgeAR** [comment]
@mavrick please post a test for this. I'm not able to reproduce this.

**Comment by mamta-dhaka** [comment]
getting 'ReplyError: ERR syntax error' error even though data is getting set, 
await this.msetAsync(['key', 'data']);
can someone help?
