### ISSUE TITLE
Ubuntu 12.04.2 LTS createClient  connect ECONNREFUSED

### ISSUE THREAD

**Issue by loretoparisi** [NodeRedis/node_redis#771]
In Ubuntu

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.2 LTS
Release:	12.04
Codename:	precise
```
connecting to a Redis instance (password protected)

```javascript
> redis=require("redis")
> client=redis.createClient(6379,'my-redis-instance.net')
```

I have a connection refused error like

```javascript
> 
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Redis connection to my-redis-instance.net:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/home/admin/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/home/admin/node_modules/redis/index.js:106:14)
    at Socket.emit (events.js:67:17)
    at Array.0 (net.js:319:25)
    at EventEmitter._tickCallback (node.js:192:41)
```

before sending the password:

```javascript
client.auth(password, function() {
    	Logger.log('Redis client connected');
  	})
```

The redis node is up and running. It is a Redis Cache on Microsoft Azure. I'm able to connect via python redis module:

```python
self.instance = redis.StrictRedis(
            host='my-redis-instance.net',
            port=6379,
            db=0,
            password=myPass)
```

Also it properly connects via telnet

```shell
$ telnet my-redis-instance.net 6379
Trying xx.xxx.xx.xx...
Connected to my-redis-instance.net.
Escape character is '^]'.
```

**Comment by loretoparisi** [comment]
I finally realized that it was node. I had version 0.6.12
Upgrading node to the latest version the socket connection now it works.

```
$ node -v
v0.12.4
```
