### ISSUE TITLE
ECONNREFUSED (New to redis)

### ISSUE THREAD

**Issue by MajorErection** [NodeRedis/node_redis#787]
So I decided to try out redis in node and I've been getting this error

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (C:\KeytoBtc\node_modules\redis\index.js:196:24)
    at Socket.<anonymous> (C:\KeytoBtc\node_modules\redis\index.js:106:14)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickCallback (node.js:355:11)

**Comment by erinspice** [comment]
Please provide your Redis config and your code at the very least. That error is the correct behavior if you don't currently have Redis running and bound to 127.0.0.1:6379.

**Comment by MajorErection** [comment]
Nevermind, I didn't understand what redis was but now I do, all I needed to do was to get the server started. Thanks for the reply anyways
