### ISSUE TITLE
fix intermitent failures in Windows CI tests

### ISSUE THREAD

**Issue by bcoe** [NodeRedis/node_redis#880]
We are observing intermittent failures in our Windows CI tests, It's likely that this demonstrates actual race conditions in the node_redis client:

```sh
 1) The node_redis client using options: detect_buffers: true;  using javascript and IPv4 unref exits subprocess as soon as final command is processed:
     Error: unref subprocess timed out
      at Error (native)
      at null._onTimeout (C:\projects\node-redis\test\node_redis.spec.js:423:37)
 
  2) The node_redis client using options: detect_buffers: true;  using javascript and IPv4 socket_nodelay true fires client.on('ready'):
     Uncaught AssertionError: null === 0
      at ChildProcess.<anonymous> (C:\projects\node-redis\test\node_redis.spec.js:428:32)
      at maybeClose (child_process.js:1015:16)
      at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

```sh
  1) publish/subscribe using options:  using javascript and IPv4 subscribe handles SUB_UNSUB_MSG_SUB:
     TypeError: Cannot read property '0' of undefined
      at Context.module.exports.serverVersionAtLeast (C:\projects\node-redis\test\helper.js:99:24)
      at Context.<anonymous> (C:\projects\node-redis\test\pubsub.spec.js:139:59)
      at callFnAsync (C:\projects\node-redis\node_modules\mocha\lib\runnable.js:306:8)
      at Test.Runnable.run (C:\projects\node-redis\node_modules\mocha\lib\runnable.js:261:7)
      at Runner.runTest (C:\projects\node-redis\node_modules\mocha\lib\runner.js:421:10)
      at C:\projects\node-redis\node_modules\mocha\lib\runner.js:528:12
      at next (C:\projects\node-redis\node_modules\mocha\lib\runner.js:341:14)
      at C:\projects\node-redis\node_modules\mocha\lib\runner.js:351:7
      at next (C:\projects\node-redis\node_modules\mocha\lib\runner.js:283:14)
      at Immediate._onImmediate (C:\projects\node-redis\node_modules\mocha\lib\runner.js:319:5)
```

```sh
  1) The node_redis client using options:  using javascript and IPv4 when connected when redis closes unexpectedly monitor monitors commands on all other redis clients:
     Error: Redis connection gone from close event.
      at RedisClient.connection_gone (C:\projects\node-redis\index.js:9:25044)
      at Socket.<anonymous> (C:\projects\node-redis\index.js:9:5432)
      at TCP.close (net.js:485:12)
```

```sh
1) The node_redis client using options: detect_buffers: true;  using javascript and IPv4 when connected when redis closes unexpectedly monitor monitors commands on all other redis clients:
     Error: Redis connection gone from close event.
      at RedisClient.connection_gone (C:\projects\node-redis\index.js:9:25044)
      at Socket.<anonymous> (C:\projects\node-redis\index.js:9:5432)
      at TCP._onclose (net.js:469:12)
```

We should put some time into squashing these bugs, since they are likely demonstrating real issues with the client that appear more easily in a Windows environment.

CC: @brycebaril @BridgeAR @mranney @erinspice @blainsmith

**Comment by BridgeAR** [comment]
@bcoe the failures are very unlikely a race condition, as node_redis does not work async. The logic itself is always executed sync and only the return values are returned in the next tick (sync though) - reconnection is of course async.

The failures are (at least partly) very likely the result of a regression in the js parser. My best guess is that I introduced that bug here: 5a2b54fd2f83825f3f4db59b5dc89989173d04a8. As soon as I have a test case and a bit of time I'll fix that issue. The different failing tests are likely just subsequent faults.

To realize such issues sooner in near future I'll also add the hiredis parser to the windows test setup. That way we'd see that the tests only fail with the js parser and it's easier to investigate that.
