### ISSUE TITLE
Node_redis 2.3.0 and node 0.10.22 cannot connect to socket

### ISSUE THREAD

**Issue by shezarkhani** [NodeRedis/node_redis#913]
Hi,
I have a local version of redis (2.8.19) running on local and listening to a socket. Upgrading to the latest node_redis build outputs this:
```
Error: Redis connection lost and commands aborted in uncertain state. They might have been processed.
    at RedisClient.connection_gone (/Users/sasanhezarkhani/MyWork/node_modules/redis/index.js:547:17)
    at Socket.<anonymous> (/Users/sasanhezarkhani/MyWork/node_modules/redis/index.js:125:14)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

I'm going to try and see what the issue is, but it started after upgrading from `2.2.5` to `2.3.0`

**Comment by BridgeAR** [comment]
@shezarkhani do you have a reproducible test for me? The error is indeed new but needed: a command was fired and the connection was lost before redis returned an answer. Therefor node_redis can't tell what happend with that command and returns an error.

**Comment by BridgeAR** [comment]
Ping @shezarkhani

**Comment by shezarkhani** [comment]
@BridgeAR Sorry, I didn't notice your comments here. I'll try and write a test that makes it happen consistently and let you know.

**Comment by shezarkhani** [comment]
@BridgeAR seems like it has something to do with big buffers and using a multi. Here is a part of my debug log. Note that there is a lot more of those `hset`s.

```
...
$4
hset
) has Buffer arguments
send_command: buffer send 34 bytes
send_command: buffer send 10 bytes
send_command: buffer send 81805 bytes
Send command (*4
$4
hset
) has Buffer arguments
send_command: buffer send 34 bytes
send_command: buffer send 6 bytes
send_command: buffer send 129418 bytes
Send localhost:6379 id 11: *1
$4
exec

Net read function () {
  if (this._handle && this._handle.getsockname) {
    return this._handle.getsockname();
  }
  return null;
} id undefined
```

**Comment by BridgeAR** [comment]
@shezarkhani would you be so kind and provide me some code that you use? And the error you just posted is another one than the one you posted the first time?

**Comment by shezarkhani** [comment]
Hi @BridgeAR 
Sorry for the late reply, I was out again. Here is a piece of code that kind of simulates what we do. (The loops are there so that we make a big payload. We don't actually submit 100 hsets)

```js
var redis = require('redis');
var step = require('step');
var zlib = require('zlib');

var redisClient = redis.createClient('/tmp/redis.sock', {
  detect_buffers: true
});

// Some random object created from http://beta.json-generator.com/
var test_obj = {"_id":"5642c4c33d4667c4a1fefd99","index":0,"guid":"5baf1f1c-7621-41e7-ae7a-f8c6f3199b0f","isActive":true,"balance":"$1,028.63","picture":"http://placehold.it/32x32","age":31,"eyeColor":"green","name":{"first":"Shana","last":"Long"},"company":"MANGLO","email":"shana.long@manglo.us","phone":"+1 (926) 405-3105","address":"747 Dank Court, Norfolk, Ohio, 1112","about":"Eu pariatur in nisi occaecat enim qui consequat nostrud cupidatat id. Commodo commodo dolore esse irure minim quis deserunt anim laborum aute deserunt et est. Quis nisi laborum deserunt nisi quis.","registered":"Friday, April 18, 2014 9:56 AM","latitude":"74.566613","longitude":"-11.660432","tags":[7,"excepteur"],"range":[0,1,2,3,4,5,6,7,8,9],"friends":[3,{"id":1,"name":"Schultz Dyer"}],"greeting":"Hello, Shana! You have 5 unread messages.","favoriteFruit":"strawberry"};

// To demonstrate a big payload for hash set field values, let's create a big array
var test_arr = [];
for (var a=0;a<80;a++) {
  var new_obj = JSON.parse(JSON.stringify(test_obj));
  test_arr.push(new_obj)
}

var json = JSON.stringify(test_arr);
step(
  function zip() {
    zlib.deflate(new Buffer(json), this);
  },

  function commit(err, buffer) {
    if (err) {
      console.log("ERROR", err);
      process.exit(1);
    }

    var multi = redisClient.multi();
    multi.del('SOME_KEY');

    for (var i=0;i<100;i++) {
      multi.hset('SOME_KEY', 'SOME_FIELD'+i, buffer);
    }

    multi.exec(function done() {
      console.log("DONE...");
      process.exit(0);
    });
  }
);```

**Comment by shezarkhani** [comment]
(accidentally removed my last comment)
Hi @BridgeAR,
Sorry for going away again. This is kind of like the code we have that generates that error. Note that the loops are there to show that this happens with big payloads. (We don't actually do this)

```js
var redis = require('redis');
var step = require('step');
var zlib = require('zlib');

var redisClient = redis.createClient('/tmp/redis.sock', {
  detect_buffers: true
});

// Some random object created from http://beta.json-generator.com/
var test_obj = {"_id":"5642c4c33d4667c4a1fefd99","index":0,"guid":"5baf1f1c-7621-41e7-ae7a-f8c6f3199b0f","isActive":true,"balance":"$1,028.63","picture":"http://placehold.it/32x32","age":31,"eyeColor":"green","name":{"first":"Shana","last":"Long"},"company":"MANGLO","email":"shana.long@manglo.us","phone":"+1 (926) 405-3105","address":"747 Dank Court, Norfolk, Ohio, 1112","about":"Eu pariatur in nisi occaecat enim qui consequat nostrud cupidatat id. Commodo commodo dolore esse irure minim quis deserunt anim laborum aute deserunt et est. Quis nisi laborum deserunt nisi quis.","registered":"Friday, April 18, 2014 9:56 AM","latitude":"74.566613","longitude":"-11.660432","tags":[7,"excepteur"],"range":[0,1,2,3,4,5,6,7,8,9],"friends":[3,{"id":1,"name":"Schultz Dyer"}],"greeting":"Hello, Shana! You have 5 unread messages.","favoriteFruit":"strawberry"};

// To demonstrate a big payload for hash set field values, let's create a big array
var test_arr = [];
for (var a=0;a<80;a++) {
  var new_obj = JSON.parse(JSON.stringify(test_obj));
  test_arr.push(new_obj)
}

var json = JSON.stringify(test_arr);
step(
  function zip() {
    zlib.deflate(new Buffer(json), this);
  },

  function commit(err, buffer) {
    if (err) {
      console.log("ERROR", err);
      process.exit(1);
    }

    var multi = redisClient.multi();
    multi.del('SOME_KEY');

    for (var i=0;i<100;i++) {
      multi.hset('SOME_KEY', 'SOME_FIELD'+i, buffer);
    }

    multi.exec(function done() {
      console.log("DONE...");
      process.exit(0);
    });
  }
);
```

However, after running this, I noticed that if I call the `exec` function in the `nextTick` I cannot reproduce the error.

**Comment by BridgeAR** [comment]
@shezarkhani would you be so kind and verify that the issue is fixed? :)

**Comment by shezarkhani** [comment]
@BridgeAR :+1: Thanks! It's fixed.
