### ISSUE TITLE
Connection string must use "redis:" protocol

### ISSUE THREAD

**Issue by bdefore** [NodeRedis/node_redis#927]
I'm using the connect-redis library which uses redis as a dependency (^2.1.0) https://github.com/tj/connect-redis/blob/master/package.json#L17 and began seeing this error with a fresh npm install:

```
[1] [piping] error given was: Error: Connection string must use the "redis:" protocol
[1]     at Object.createClient (/[REDACTED]/node_modules/express-jwt-proxy/node_modules/connect-redis/node_modules/redis/index.js:1298:23)
[1]     at new RedisStore (/[REDACTED]/node_modules/express-jwt-proxy/node_modules/connect-redis/lib/connect-redis.js:72:27)
[1]     at setupSessionManager (/[REDACTED]/node_modules/express-jwt-proxy/lib/index.js:201:14)
[1]     at Object.exports.default (/[REDACTED]/node_modules/express-jwt-proxy/lib/index.js:226:3)
[1]     at setupAuth (/[REDACTED]/bin/start_es6.js:63:32)
[1]     at Object.<anonymous> (/[REDACTED]/bin/start_es6.js:103:18)
[1]     at Module._compile (module.js:434:26)
[1]     at normalLoader (/[REDACTED]/node_modules/babel-core/lib/api/register/node.js:199:5)
[1]     at Object.require.extensions.(anonymous function) (/[REDACTED]/node_modules/babel-core/lib/api/register/node.js:216:7)
[1]     at Module.load (module.js:355:32)
```

I don't think I've seen this error before. Changing my redis url to `redis://127.0.0.1:6379` instead of `http://127.0.0.1:6379`. Wouldn't this be a regression for 2.1.x?

**Comment by renaesop** [comment]
yeah,I also met this problem

**Comment by BridgeAR** [comment]
I added the check so no one could come up with e.g. `user:pass@host:port` and pass that as url.

In that case what's going to be parsed is:
* protocol: user // Faulty
* auth: pass // Faulty
* host: host
* port: port

I'll check how to improve the validation though.

**Comment by lepfhty** [comment]
also broke our service

**Comment by BridgeAR** [comment]
@bdefore @renaesop @lepfhty what did you use as url string before?

**Comment by bdefore** [comment]
`http://127.0.0.1:6379` ... switching to `redis://127.0.0.1:6379` has worked fine since i encountered the issue.

**Comment by puzrin** [comment]
@BridgeAR could you also add db index selection s in https://github.com/ddollar/redis-url#usage? Or this already was rejected for some reasons?

**Comment by BridgeAR** [comment]
@puzrin this is going to be included in the next version. The new url schema is going to be the one from [IANA](http://www.iana.org/assignments/uri-schemes/prov/redis): `[redis:]//[user][:password@][host][:port][/db-number][?option=value[&password=bar]]`. I also changed the protocol check to not be as strict with the redis protocol and accept other protocols or omitting the procotol from now on too.

**Comment by puzrin** [comment]
@BridgeAR gread news, thanks a lot!

**Comment by puzrin** [comment]
@BridgeAR thanks for new schema support! Any estimates when we can see this in new release?

**Comment by Hunchmun** [comment]
Hey all,

I see this change occurred over a year ago, but is there any option to use Unix sockets instead of the redis protocol? 

Redis clients can accept "/tmp/redis.sock" as a valid connection and this increases the throughput for intensive localised applications,

Has there been any other discussion on this?

Thanks, and please enjoy the holidays,

**Comment by stockholmux** [comment]
@Hunchmun See the [readme](https://github.com/NodeRedis/node_redis#rediscreateclient). Cheers.
