### ISSUE TITLE
quit() throws when prefix option is set on client

### ISSUE THREAD

**Issue by mattwiller** [NodeRedis/node_redis#940]
When the redis client has the prefix option set, any call to client.quit() will throw an error:

```
> var redis = require('redis');
undefined
> var client = redis.createClient({prefix: 'foo:'});
undefined
> client.quit();
Error: Unknown command quit
    at Object.exports.getKeyIndexes (/Users/mwiller/test/node_modules/redis/node_modules/redis-commands/index.js:62:11)
    at RedisClient.send_command (/Users/mwiller/test/node_modules/redis/index.js:814:32)
    at RedisClient.(anonymous function).RedisClient.(anonymous function) (/Users/mwiller/test/node_modules/redis/index.js:971:21)
    at repl:1:8
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
```

It looks like this is because the `QUIT` command is not technically listed as a Redis command, either in the redis-commands module or in the output of the redis `COMMAND INFO` command (as of redis 3.0.3):

```
$ redis-cli
127.0.0.1:6379> command info quit
1) (nil)
```

**Comment by BridgeAR** [comment]
True. There is already a pull request from @badboy in redis to fix this. But I also have a intermediate local fix for this for redis-commands. I'll publish a fix in redis-commands tomorrow or later on.

**Comment by BridgeAR** [comment]
Reference https://github.com/antirez/redis/pull/2982

**Comment by mattwiller** [comment]
@BridgeAR Cool, thanks!  For now, our use case is limited enough that we can just add the prefix in our application until a fix lands.

**Comment by BridgeAR** [comment]
Fixed and released on npm. Please run npm update.
