### ISSUE TITLE
Redis connection to xxxxxx failed - read ECONNRESET

### ISSUE THREAD

**Issue by bartonhammond** [NodeRedis/node_redis#980]
Please advise what info and how to obtain it, to help

Running on OpenShift
Node Version: v4.2.3 
Redis Server: 2.18.24
Node_Redis:   2.4.2

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Redis connection to xxxxx.com:50681 failed - read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TCP.onread (net.js:544:26)
DEBUG: Program node build/server.js exited with code 1
DEBUG: Starting child process with 'node build/server.js'
Server is running: http://ex-std-node496.prod.rhcloud.com:8080
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Redis connection to xxxxx.rhcloud.com:50681 failed - connect ECONNREFUSED 172.16.2.86:50681
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
DEBUG: Program node build/server.js exited with code 1
DEBUG: Starting child process with 'node build/server.js'
Server is running: http://ex-std-node496.prod.rhcloud.com:8080
events.js:141
      throw er; // Unhandled 'error' event
```

**Comment by bartonhammond** [comment]
Got a little more info today:

```
CreateGetStargazersForRepoByPageJobProcessor.page 115
160211/122616.785, [response], http://ex-std-node496.prod.rhcloud.com:8080: get / {} 200 (7ms) 
160211/122618.794, [response], http://ex-std-node496.prod.rhcloud.com:8080: get / {} 200 (5ms) 
160211/122620.801, [response], http://ex-std-node496.prod.rhcloud.com:8080: get / {} 200 (8ms) 
160211/122434.112, [response], http://ex-std-node496.prod.rhcloud.com:8080: get /kue/getmapbox/d88d9c7f2879f4319f93be032a92a1326db12031/limetext/lime/ {} 200 (108439ms) 
160211/122622.552, [log,internal,implementation,error], data: {"code":"UNCERTAIN_STATE","command":"ZRANGE","domain":{"domain":null,"_events":{},"_eventsCount":1,"members":[]},"domainThrown":true}
Debug: internal, implementation, error 
    Error: Redis connection lost and commands aborted in uncertain state. They might have been processed.
    at RedisClient.connection_gone (/var/lib/openshift/56a387302d5271a0390000e9/app-root/runtime/repo/node_modules/redis/index.js:569:17)
    at Socket.<anonymous> (/var/lib/openshift/56a387302d5271a0390000e9/app-root/runtime/repo/node_modules/redis/index.js:144:14)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
events.js:141
      throw er; // Unhandled 'error' event
      ^
```

**Comment by BridgeAR** [comment]
The server connection is lost and as the errors are unhandled I guess you did not attach a event listener for it to the client?

UNCERTAIN_STATE means that the connection got lost after firing a command but without the answer being returned. Your call took 108439ms so that's a huge delay...

Please check your server connection and add a error handler. That is likely all that I can help you with right now.

**Comment by bartonhammond** [comment]
@BridgeAR I do not have a event listener defined - didn't know I needed to.

Could you provide an example of what I'm needing to do?  I looked through README.md and don't see specifically what to do within the error handler.

**Comment by bartonhammond** [comment]
@BridgeAR I added the following code:
```
  redisClient.on('error', function (er) {
    console.trace('Here I am'); 
    console.error(er.stack); 
  });
```

```
etStargazersByPage bevacqua:dragula:115
February 11th 2016, 12:57:02 pm /repos/bevacqua/dragula/stargazers?page=115&per_page=100&client_id=06bb3ce00732d2c19dc0&client_secret=031c8b66cfc758bae3dcea0890ad6f691b494a57 ratelimit: 5000 remaining: 4769 dateOk: February 11th 2016, 1:22:50 pm 1455214970
CreateGetStargazersForRepoByPageJobProcessor.page 115
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Redis connection to 56a388737628e1252200004b-bartonhammond.rhcloud.com:50681 failed - read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TCP.onread (net.js:544:26)
DEBUG: Program node build/server.js exited with code 1
DEBUG: Starting child process with 'node build/server.js'
Server is running: http://ex-std-node496.prod.rhcloud.com:8080
Trace: Here I am
    at RedisClient.<anonymous> (/var/lib/openshift/56a387302d5271a0390000e9/app-root/runtime/repo/build/database/redis.js:57:13)
    at emitOne (events.js:77:13)
    at RedisClient.emit (events.js:169:7)
    at RedisClient.on_error (/var/lib/openshift/56a387302d5271a0390000e9/app-root/runtime/repo/node_modules/redis/index.js:216:10)
    at Socket.<anonymous> (/var/lib/openshift/56a387302d5271a0390000e9/app-root/runtime/repo/node_modules/redis/index.js:135:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
Error: Redis connection to 56a388737628e1252200004b-bartonhammond.rhcloud.com:50681 failed - connect ECONNREFUSED 172.16.2.86:50681
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
events.js:141
      throw er; // Unhandled 'error' event

```

**Comment by BridgeAR** [comment]
The first and the third error is still not handled. Are you using different client instances?

**Comment by bartonhammond** [comment]
Why closed?
I am using Kue and it also uses Redis and I provide the configuration pieces as it uses a different Redis client.
What should I do?
I have contacted Openshift

**Comment by bartonhammond** [comment]
I see that Kue can share Redis client.  I will change when I get back.

**Comment by bartonhammond** [comment]
After changing Kue to share the Redis client:

I opened issue w/ Kue also

```
~/projects/stargazers/openshift-stargazers (master)$ npm start

> stargazers-server@0.0.1 start /Users/barton/projects/stargazers/openshift-stargazers
> node build/server.js

(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at RedisClient.addListener (events.js:239:17)
    at Object.exports.createClient (/Users/barton/projects/stargazers/openshift-stargazers/node_modules/kue/lib/redis.js:64:12)
    at Worker.getJob (/Users/barton/projects/stargazers/openshift-stargazers/node_modules/kue/lib/queue/worker.js:267:70)
    at Worker.start (/Users/barton/projects/stargazers/openshift-stargazers/node_modules/kue/lib/queue/worker.js:82:8)
    at Queue.process (/Users/barton/projects/stargazers/openshift-stargazers/node_modules/kue/lib/kue.js:332:41)
    at GetMapData.init (/Users/barton/projects/stargazers/openshift-stargazers/build/newlib/jobs/mapdata/GetMapData.js:36:18)
    at _queue (/Users/barton/projects/stargazers/openshift-stargazers/build/newlib/Queue.js:112:39)
    at Object.queue (/Users/barton/projects/stargazers/openshift-stargazers/build/newlib/Queue.js:141:12)
    at Object.<anonymous> (/Users/barton/projects/stargazers/openshift-stargazers/build/routes/jobs/handlers.js:36:43)
    at Module._compile (module.js:435:26)
Server is running: http://Bartons-MBP.centurylink.net:5000
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context
    at JavascriptReplyParser._parseResult (/Users/barton/projects/stargazers/openshift-stargazers/node_modules/redis/lib/parsers/javascript.js:43:16)
    at JavascriptReplyParser.try_parsing (/Users/barton/projects/stargazers/openshift-stargazers/node_modules/redis/lib/parsers/javascript.js:114:21)
    at JavascriptReplyParser.run (/Users/barton/projects/stargazers/openshift-stargazers/node_modules/redis/lib/parsers/javascript.js:135:22)
    at JavascriptReplyParser.execute (/Users/barton/projects/stargazers/openshift-stargazers/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/Users/barton/projects/stargazers/openshift-stargazers/node_modules/redis/index.js:131:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

```

**Comment by bartonhammond** [comment]
I've updated my configuration w/ Kue such that it is also now use node_redis.  But I still get the error:

I've opened a support ticket with OpenShift also.
```
February 11th 2016, 7:46:54 pm /repos/defunkt/jquery-pjax/stargazers?page=130&per_page=100&access_token=d88d9c7f2879f4311 ratelimit: 5000 remaining: 4870 dateOk: February 11th 2016, 8:45:08 pm 1455241508
CreateGetStargazersForRepoByPageJobProcessor.page 130
ProcessorClass.count: 116/129
ProcessorClass.count: 130/130
February 11th 2016, 7:46:55 pm /repos/lukehoban/es6features/stargazers?page=121&per_page=100&access_token=2ac7346f329b61384941 ratelimit: 5000 remaining: 4879 dateOk: February 11th 2016, 8:45:15 pm 1455241515
CreateGetStargazersForRepoByPageJobProcessor.page 121
160211/194656.335, [response], http://ex-std-node496.prod.rhcloud.com:8080: get / {} 200 (6ms) 
160211/194658.342, [response], http://ex-std-node496.prod.rhcloud.com:8080: get / {} 200 (8ms) 
160211/194700.354, [response], http://ex-std-node496.prod.rhcloud.com:8080: get / {} 200 (20ms) 
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Redis connection to 56a388737628e1252200004b-bartonhammond.rhcloud.com:50681 failed - read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TCP.onread (net.js:544:26)
DEBUG: Program node build/server.js exited with code 1
DEBUG: Starting child process with 'node build/server.js'
Server is running: http://ex-std-node496.prod.rhcloud.com:8080
Trace: Here I am
    at RedisClient.<anonymous> (/var/lib/openshift/56a387302d5271a0390000e9/app-root/runtime/repo/build/database/redis.js:56:13)
    at emitOne (events.js:77:13)
    at RedisClient.emit (events.js:169:7)
    at RedisClient.on_error (/var/lib/openshift/56a387302d5271a0390000e9/app-root/runtime/repo/node_modules/redis/index.js:216:10)
    at Socket.<anonymous> (/var/lib/openshift/56a387302d5271a0390000e9/app-root/runtime/repo/node_modules/redis/index.js:135:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
Error: Redis connection to 56a388737628e1252200004b-bartonhammond.rhcloud.com:50681 failed - connect ECONNREFUSED 172.16.2.86:50681
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Redis connection to 56a388737628e1252200004b-bartonhammond.rhcloud.com:50681 failed - connect ECONNREFUSED 172.16.2.86:50681
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
DEBUG: Program node build/server.js exited with code 1
DEBUG: Starting child process with 'node build/server.js'
Server is running: http://ex-std-node496.prod.rhcloud.com:8080
Trace: Here I am
    at RedisClient.<anonymous> (/var/lib/openshift/56a387302d5271a0390000e9/app-root/runtime/repo/build/database/redis.js:56:13)
    at emitOne (events.js:77:13)
    at RedisClient.emit (events.js:169:7)
    at RedisClient.on_error (/var/lib/openshift/56a387302d5271a0390000e9/app-root/runtime/repo/node_modules/redis/index.js:216:10)
    at Socket.<anonymous> (/var/lib/openshift/56a387302d5271a0390000e9/app-root/runtime/repo/node_modules/redis/index.js:135:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
Error: Redis connection to 56a388737628e1252200004b-bartonhammond.rhcloud.com:50681 failed - connect ECONNREFUSED 172.16.2.86:50681
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Redis connection to 56a388737628e1252200004b-bartonhammond.rhcloud.com:50681 failed - connect ECONNREFUSED 172.16.2.86:50681
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
DEBUG: Program node build/server.js exited with code 1
DEBUG: Starting child process with 'node build/server.js'
Server is running: http://ex-std-node496.prod.rhcloud.com:8080
```

**Comment by BridgeAR** [comment]
There are unhandled errors, so there are definitely redis connections open that do not have a attached error listener.

I closed the issue as I'm quite certain there is not much more that I can help you with in this case. The thrown errors are not thrown by node_redis directly but by the net module from NodeJS. The error is just passed to the library and emitted from node_redis. I hope you found a solution for it in the meanwhile.

**Comment by jalfcolombia** [comment]
Hello, I have the same problem and I have no idea how to fix it

**Comment by valdorvaldor** [comment]
I'm having same issue:

**CLIENT: 3.0.2
REDIS: 5.0.3**

- Running Inside GCLOUD ( latency ~10ms )
- After started, the app starts PINGING the redis server every 30 seconds
- Server crashes after 4 minutes (usually), just after PING #8 ( PING timestamp === ERROR timestamp )
- not a single event es registered in the log ( end, error, uncaughtException, reconnecting  )
- I've tried ECHO instead of PING but I got same results.

```
var redis__create_ping = ( client ) => {
        client.ping = setInterval(( )=>{
                let timestamp = ( new Date() ).getTime();
                client.instance.ping(  (error, pong ) => {
                        if( error ){
                                console.error( '\n<PING ERROR>', client.name, client.index );
                                console.error( error );
                        }
                        else {
                                if( __.DEBUG ){
                                        console.log( '\n<PING>', client.name, client.index, (new Date()).getTime() - timestamp );
                                }
                        };
                });
        },  30000);
};

var redis__connect = ( args , success, fail ) => {
        let { index, name } = args;
        let client = { name, index };
        let host = ___.REDIS.HOST;
        let port = ___.REDIS.PORT;
        let cli = redis.createClient({ host, port, db: index, socket_keepalive: true });
        cli.on('connect',  ready => {
                if( __.DEBUG ) console.info('\n<CONNECT>', name, index  );
                client.instance = cli;
                redis__create_ping( client );
                CLIENTS[name] = client;
                success( true );
        });

        cli.on('ready', () => {
                if( __.DEBUG ) console.info( '\n<READY>', name, index );
        });

        cli.on('reconnecting', () => {
                if( __.DEBUG ) console.info( '\n<RECONNECTING>', name, index );
        });

        cli.on('end', () => {
                if( __.DEBUG ) console.info('\n<END>', name, index  );
        });

        cli.on('uncaughtException',  error  => {
                console.error('\n<UNCAUGHT-EXCEPTION>', name, index  );
                console.error( error  );
        });

        cli.on('error', error => {
                console.error('\n<ERROR>', name, index  );
                console.error( error );
        });
};

```

**LOG**
```
...
2021-01-27 15:59:42.472 EST<PING> REDIS_CLIENT_BLOCKED_NUMBERS_WRITE 11 4
Default
2021-01-27 15:59:42.480 ESTevents.js:292
Default
2021-01-27 15:59:42.480 EST throw er; // Unhandled 'error' event
Default
2021-01-27 15:59:42.480 EST ^
Default
2021-01-27 15:59:42.480 EST
Default
2021-01-27 15:59:42.480 ESTError: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Default
2021-01-27 15:59:42.480 ESTEmitted 'error' event on RedisClient instance at:
Default
2021-01-27 15:59:42.480 EST at RedisClient.on_error (/opt/app/node_modules/redis/index.js:341:14)
Default
2021-01-27 15:59:42.480 EST at Socket.<anonymous> (/opt/app/node_modules/redis/index.js:222:14)
Default
2021-01-27 15:59:42.480 EST at Socket.emit (events.js:315:20)
Default
2021-01-27 15:59:42.480 EST at emitErrorNT (internal/streams/destroy.js:106:8)
Default
2021-01-27 15:59:42.480 EST at emitErrorCloseNT (internal/streams/destroy.js:74:3)
Default
2021-01-27 15:59:42.480 EST at processTicksAndRejections (internal/process/task_queues.js:80:21) {
Default
2021-01-27 15:59:42.480 EST errno: -104,
Default
2021-01-27 15:59:42.480 EST code: 'ECONNRESET',
Default
2021-01-27 15:59:42.480 EST syscall: 'read'
Default
2021-01-27 15:59:42.480 EST}
Warning
2021-01-27 15:59:46.579 ESTContainer called exit(1).
```
